import { workflow, node, trigger, ifElse, expr } from '@n8n/workflow-sdk';

// 12 - NOYA Outbound Email Executor v1
// Creates exactly one UNSENT Gmail draft for an Adam-approved outbound_emails row. The webhook
// accepts only an outbound id; recipient, subject and body always come from the database row
// that outbound_approve() / outbound_approve_candidate() created after every gate passed.
// Draft only (Adam, 8 Oct 2026: approve never means send): there is no send node, and the
// database refuses SEND rows (constraint outbound_emails_draft_only, outbound_claim).
// No schedule, no loop, no batch; noya@noyaconcierge.com only. Adam presses Send in Gmail.
// Generated by n8n/gen_12_outbound_email_executor.py - edit that file, not this one.

// Plain-text draft -> light HTML: paragraphs, soft line joins, NOYA email / site / Instagram links.
const HTML_BODY = "{{ (function (b) {var esc = function (s) { return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }; var lnk = function (s) { return s.replace(/([A-Za-z0-9._%+-]+)@noyaconcierge\.com/g, '<a href="mailto:$1@noyaconcierge.com" style="color:#222222">$1@noyaconcierge.com</a>').replace(/(?<![@\w.\/"])noyaconcierge\.com(?![^<]*<\/a>)/g, '<a href="https://noyaconcierge.com" style="color:#222222">noyaconcierge.com</a>').replace(/(?<![\w.])@noyaconcierge(?![\w.])/g, '<a href="https://www.instagram.com/noyaconcierge/" style="color:#222222">@noyaconcierge</a>'); }; var paras = String(b || '').replace(/\r/g, '').replace(/[\u2010\u2011\u2012]/g, '-').replace(/\u00a0/g, ' ').trim().split(/\n[ \t]*\n+/); return '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.5;color:#222222">' + paras.map(function (p) { var lines = p.trim().split('\n'), out = ''; lines.forEach(function (l, i) { out += lnk(esc(l.trim())); if (i < lines.length - 1) out += (l.trim().length >= 60 && !/[.:!?]$/.test(l.trim())) ? ' ' : '<br>'; }); return '<p style="margin:0 0 12px 0">' + out + '</p>'; }).join('') + '</div>';})($json.body) }}";

const webhook = trigger({
  type: 'n8n-nodes-base.webhook',
  version: 2.1,
  config: {
    name: 'Execute Approved Outbound',
    position: [0, 300],
    parameters: { httpMethod: 'POST', path: 'noya-outbound-execute', responseMode: 'responseNode', options: {} }
  }
});

const validateInput = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Validate Outbound Id',
    position: [220, 300],
    parameters: {
      mode: 'runOnceForAllItems',
      jsCode: "var body = ($input.first().json.body) || {};\nvar id = String(body.outbound_id || '').trim();\nif (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)) {\n  throw new Error('outbound_id must be a uuid');\n}\nreturn [{ json: { outbound_id: id } }];"
    }
  }
});

// Sender identity guard: refuse to run unless the Gmail credential is the NOYA mailbox.
const verifyMailbox = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Verify NOYA Mailbox',
    position: [440, 300],
    parameters: {
      method: 'GET',
      url: 'https://gmail.googleapis.com/gmail/v1/users/me/profile',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'gmailOAuth2',
      options: { timeout: 20000 }
    },
    credentials: { gmailOAuth2: { id: 'OMGm2CkcvDKbJTr3', name: 'NOYA Gmail' } }
  }
});

const mailboxIsNoya = ifElse({
  version: 2.2,
  config: {
    name: 'Mailbox Is NOYA?',
    position: [660, 300],
    parameters: {
      conditions: {
        options: { caseSensitive: false, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: expr('{{ $json.emailAddress }}'), operator: { type: 'string', operation: 'equals' }, rightValue: 'noya@noyaconcierge.com' }],
        combinator: 'and'
      }
    }
  }
});

const claimed = ifElse({
  version: 2.2,
  config: {
    name: 'Claimed?',
    position: [1100, 200],
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: expr('{{ $json.ok }}'), operator: { type: 'boolean', operation: 'true', singleValue: true }, rightValue: '' }],
        combinator: 'and'
      }
    }
  }
});

const gmailDraft = node({
  type: 'n8n-nodes-base.gmail',
  version: 2.2,
  config: {
    name: 'Gmail Create Draft (noya@)',
    position: [1320, 200],
    onError: 'continueErrorOutput',
    parameters: {
      resource: 'draft',
      operation: 'create',
      subject: expr('{{ $json.subject }}'),
      emailType: 'html',
      message: expr(HTML_BODY),
      options: { sendTo: expr('{{ $json.to_email }}') }
    },
    credentials: { gmailOAuth2: { id: 'OMGm2CkcvDKbJTr3', name: 'NOYA Gmail' } }
  }
});

const claim = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Claim Outbound (exactly once)',
    position: [880, 200],
    parameters: {
      method: 'POST',
      url: 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/outbound_claim',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: expr("{{ JSON.stringify({ p_outbound_id: $('Validate Outbound Id').first().json.outbound_id }) }}"),
      options: { timeout: 20000 }
    },
    credentials: { supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } }
  }
});

const completeDraft = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Record Draft In CRM',
    position: [1540, 140],
    parameters: {
      method: 'POST',
      url: 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/outbound_complete',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: expr("{{ JSON.stringify({ p_outbound_id: $('Validate Outbound Id').first().json.outbound_id, p_gmail_message_id: $json.message.id, p_gmail_thread_id: $json.message.threadId, p_gmail_draft_id: $json.id }) }}"),
      options: { timeout: 20000 }
    },
    credentials: { supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } }
  }
});

const failDraft = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Record Draft Failure',
    position: [1760, 300],
    parameters: {
      method: 'POST',
      url: 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/outbound_fail',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: expr("{{ JSON.stringify({ p_outbound_id: $('Validate Outbound Id').first().json.outbound_id, p_error: String(($json.error && ($json.error.message || $json.error)) || 'gmail draft failed') }) }}"),
      options: { timeout: 20000 }
    },
    credentials: { supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } }
  }
});

const respondDoneDraft = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: { name: 'Respond Draft Result', position: [1760, 140], parameters: { respondWith: 'json', responseBody: expr('{{ JSON.stringify($json) }}'), options: { responseCode: 200 } } }
});

const respondFailedDraft = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: { name: 'Respond Draft Failure', position: [1760, 300], parameters: { respondWith: 'json', responseBody: expr("{{ JSON.stringify({ ok: false, reason: 'PROVIDER_ERROR', detail: $json }) }}"), options: { responseCode: 502 } } }
});

const respondNotClaimed = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: { name: 'Respond Not Claimed', position: [1320, 400], parameters: { respondWith: 'json', responseBody: expr('{{ JSON.stringify($json) }}'), options: { responseCode: 409 } } }
});

const respondWrongMailbox = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: { name: 'Respond Wrong Mailbox', position: [880, 420], parameters: { respondWith: 'json', responseBody: expr("{{ JSON.stringify({ ok: false, reason: 'WRONG_MAILBOX', mailbox: $json.emailAddress }) }}"), options: { responseCode: 500 } } }
});


export default workflow('noya-12-outbound-executor', '12 - NOYA Outbound Email Executor v1')
  .add(webhook)
  .to(validateInput)
  .to(verifyMailbox)
  .to(mailboxIsNoya
    .onTrue(claim.to(claimed
      .onTrue(gmailDraft
        .onError(failDraft.to(respondFailedDraft))
        .to(completeDraft.to(respondDoneDraft)))
      .onFalse(respondNotClaimed)))
    .onFalse(respondWrongMailbox));
