import { workflow, node, trigger, ifElse, expr } from '@n8n/workflow-sdk';

// 12 - NOYA Outbound Email Executor v1
// Executes exactly one Adam-approved outbound_emails row. The webhook accepts only an
// outbound id; recipient, subject and body always come from the database row that
// outbound_approve() created after every gate passed. No schedule, no loop, no batch:
// one call sends or drafts at most one email, from noya@noyaconcierge.com only.
// Generated by n8n/gen_12_outbound_email_executor.py - edit that file, not this one.

const webhook = trigger({
  type: 'n8n-nodes-base.webhook',
  version: 2.1,
  config: {
    name: 'Execute Approved Outbound',
    position: [0, 300],
    parameters: { httpMethod: 'POST', path: 'noya-outbound-execute', responseMode: 'responseNode', options: {} }
  }
});

const validateInput = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Validate Outbound Id',
    position: [220, 300],
    parameters: {
      mode: 'runOnceForAllItems',
      jsCode: "var body = ($input.first().json.body) || {};\nvar id = String(body.outbound_id || '').trim();\nif (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)) {\n  throw new Error('outbound_id must be a uuid');\n}\nreturn [{ json: { outbound_id: id } }];"
    }
  }
});

// Sender identity guard: refuse to run unless the Gmail credential is the NOYA mailbox.
const verifyMailbox = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Verify NOYA Mailbox',
    position: [440, 300],
    parameters: {
      method: 'GET',
      url: 'https://gmail.googleapis.com/gmail/v1/users/me/profile',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'gmailOAuth2',
      options: { timeout: 20000 }
    },
    credentials: { gmailOAuth2: { id: 'OMGm2CkcvDKbJTr3', name: 'NOYA Gmail' } }
  }
});

const mailboxIsNoya = ifElse({
  version: 2.2,
  config: {
    name: 'Mailbox Is NOYA?',
    position: [660, 300],
    parameters: {
      conditions: {
        options: { caseSensitive: false, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: expr('{{ $json.emailAddress }}'), operator: { type: 'string', operation: 'equals' }, rightValue: 'noya@noyaconcierge.com' }],
        combinator: 'and'
      }
    }
  }
});

const claimed = ifElse({
  version: 2.2,
  config: {
    name: 'Claimed?',
    position: [1100, 200],
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: expr('{{ $json.ok }}'), operator: { type: 'boolean', operation: 'true', singleValue: true }, rightValue: '' }],
        combinator: 'and'
      }
    }
  }
});

const isSend = ifElse({
  version: 2.2,
  config: {
    name: 'Explicit Send?',
    position: [1320, 100],
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'strict' },
        conditions: [{ leftValue: expr('{{ $json.mode }}'), operator: { type: 'string', operation: 'equals' }, rightValue: 'SEND' }],
        combinator: 'and'
      }
    }
  }
});

const gmailSend = node({
  type: 'n8n-nodes-base.gmail',
  version: 2.2,
  config: {
    name: 'Gmail Send (noya@)',
    position: [1540, 0],
    onError: 'continueErrorOutput',
    parameters: {
      resource: 'message',
      operation: 'send',
      sendTo: expr('{{ $json.to_email }}'),
      subject: expr('{{ $json.subject }}'),
      emailType: 'text',
      message: expr('{{ $json.body }}'),
      options: { appendAttribution: false }
    },
    credentials: { gmailOAuth2: { id: 'OMGm2CkcvDKbJTr3', name: 'NOYA Gmail' } }
  }
});

const gmailDraft = node({
  type: 'n8n-nodes-base.gmail',
  version: 2.2,
  config: {
    name: 'Gmail Create Draft (noya@)',
    position: [1540, 200],
    onError: 'continueErrorOutput',
    parameters: {
      resource: 'draft',
      operation: 'create',
      subject: expr('{{ $json.subject }}'),
      emailType: 'text',
      message: expr('{{ $json.body }}'),
      options: { sendTo: expr('{{ $json.to_email }}') }
    },
    credentials: { gmailOAuth2: { id: 'OMGm2CkcvDKbJTr3', name: 'NOYA Gmail' } }
  }
});

const claim = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Claim Outbound (exactly once)',
    position: [880, 200],
    parameters: {
      method: 'POST',
      url: 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/outbound_claim',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: expr("{{ JSON.stringify({ p_outbound_id: $('Validate Outbound Id').first().json.outbound_id }) }}"),
      options: { timeout: 20000 }
    },
    credentials: { supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } }
  }
});

const completeSend = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Record Send In CRM',
    position: [1760, -60],
    parameters: {
      method: 'POST',
      url: 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/outbound_complete',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: expr("{{ JSON.stringify({ p_outbound_id: $('Validate Outbound Id').first().json.outbound_id, p_gmail_message_id: $json.id, p_gmail_thread_id: $json.threadId, p_gmail_draft_id: null }) }}"),
      options: { timeout: 20000 }
    },
    credentials: { supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } }
  }
});

const completeDraft = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Record Draft In CRM',
    position: [1760, 180],
    parameters: {
      method: 'POST',
      url: 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/outbound_complete',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: expr("{{ JSON.stringify({ p_outbound_id: $('Validate Outbound Id').first().json.outbound_id, p_gmail_message_id: $json.message.id, p_gmail_thread_id: $json.message.threadId, p_gmail_draft_id: $json.id }) }}"),
      options: { timeout: 20000 }
    },
    credentials: { supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } }
  }
});

const failSend = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Record Send Failure',
    position: [1760, 60],
    parameters: {
      method: 'POST',
      url: 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/outbound_fail',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: expr("{{ JSON.stringify({ p_outbound_id: $('Validate Outbound Id').first().json.outbound_id, p_error: String(($json.error && ($json.error.message || $json.error)) || 'gmail send failed') }) }}"),
      options: { timeout: 20000 }
    },
    credentials: { supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } }
  }
});

const failDraft = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Record Draft Failure',
    position: [1760, 300],
    parameters: {
      method: 'POST',
      url: 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/outbound_fail',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: expr("{{ JSON.stringify({ p_outbound_id: $('Validate Outbound Id').first().json.outbound_id, p_error: String(($json.error && ($json.error.message || $json.error)) || 'gmail draft failed') }) }}"),
      options: { timeout: 20000 }
    },
    credentials: { supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } }
  }
});

const respondDone = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: { name: 'Respond Result', position: [1980, 60], parameters: { respondWith: 'json', responseBody: expr('{{ JSON.stringify($json) }}'), options: { responseCode: 200 } } }
});

const respondDoneDraft = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: { name: 'Respond Draft Result', position: [1980, 240], parameters: { respondWith: 'json', responseBody: expr('{{ JSON.stringify($json) }}'), options: { responseCode: 200 } } }
});

const respondFailed = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: { name: 'Respond Failure', position: [1980, 150], parameters: { respondWith: 'json', responseBody: expr("{{ JSON.stringify({ ok: false, reason: 'PROVIDER_ERROR', detail: $json }) }}"), options: { responseCode: 502 } } }
});

const respondFailedDraft = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: { name: 'Respond Draft Failure', position: [1980, 330], parameters: { respondWith: 'json', responseBody: expr("{{ JSON.stringify({ ok: false, reason: 'PROVIDER_ERROR', detail: $json }) }}"), options: { responseCode: 502 } } }
});

const respondNotClaimed = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: { name: 'Respond Not Claimed', position: [1320, 320], parameters: { respondWith: 'json', responseBody: expr('{{ JSON.stringify($json) }}'), options: { responseCode: 409 } } }
});

const respondWrongMailbox = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: { name: 'Respond Wrong Mailbox', position: [880, 420], parameters: { respondWith: 'json', responseBody: expr("{{ JSON.stringify({ ok: false, reason: 'WRONG_MAILBOX', mailbox: $json.emailAddress }) }}"), options: { responseCode: 500 } } }
});


export default workflow('noya-12-outbound-executor', '12 - NOYA Outbound Email Executor v1')
  .add(webhook)
  .to(validateInput)
  .to(verifyMailbox)
  .to(mailboxIsNoya
    .onTrue(claim.to(claimed
      .onTrue(isSend
        .onTrue(gmailSend
          .onError(failSend.to(respondFailed))
          .to(completeSend.to(respondDone)))
        .onFalse(gmailDraft
          .onError(failDraft.to(respondFailedDraft))
          .to(completeDraft.to(respondDoneDraft))))
      .onFalse(respondNotClaimed)))
    .onFalse(respondWrongMailbox));
