#!/usr/bin/env python3
"""Generate n8n/workflow_23_email_intelligence.js (Workflow SDK) from the code files in n8n/w23/.

Usage: python3 n8n/build_w23.py   (then create / update the live workflow with the n8n MCP tools)
"""
import json
import pathlib

H = pathlib.Path(__file__).parent
CODE = {k: (H / 'w23' / f).read_text() for k, f in [('bs', 'build_searches.js'), ('pp', 'plan_pages.js'), ('ee', 'extract_evidence.js'),
                                                       ('vf', 'verify.js'), ('ne', 'no_evidence.js')]}
SUPABASE = 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/'
SUPABASE_CRED = "{ supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } }"


def rpc(var, name, fn, body, extra=''):
    return (f"const {var} = node({{ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: {{ name: {json.dumps(name)}, retryOnFail: true, maxTries: 3, waitBetweenTries: 2000,{extra}\n"
            f"  parameters: {{ method: 'POST', url: '{SUPABASE}{fn}', authentication: 'predefinedCredentialType', nodeCredentialType: 'supabaseApi',\n"
            f"    sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: expr({json.dumps(body)}), options: {{ timeout: 60000 }} }},\n"
            f"  credentials: {SUPABASE_CRED} }} }});")


def code(var, name, key):
    return f"const {var} = node({{ type: 'n8n-nodes-base.code', version: 2, config: {{ name: {json.dumps(name)}, parameters: {{ mode: 'runOnceForAllItems', jsCode: {json.dumps(CODE[key])} }} }} }});"


def is_true(var, name, field):
    return (f"const {var} = ifElse({{ version: 2.2, config: {{ name: {json.dumps(name)}, parameters: {{ conditions: {{ options: {{ caseSensitive: true, leftValue: '', typeValidation: 'loose' }},\n"
            f"  conditions: [{{ leftValue: expr({json.dumps('{{ ' + field + ' }}')}), operator: {{ type: 'boolean', operation: 'true', singleValue: true }} }}], combinator: 'and' }} }} }} }});")


SRC = "\n".join([
    "import { workflow, node, trigger, ifElse, expr } from '@n8n/workflow-sdk';",
    "",
    "// 23 - NOYA Email Intelligence (Adam, 8 Oct 2026). Works the email gap queue: qualified companies with a commercial angle and no",
    "// usable named-person or department email. Email-first research: the company's own contact, team, partnerships, press and",
    "// media-kit pages are read; addresses indexed anywhere on its domain (press releases, speaker bios, PDFs) and its Instagram bio",
    "// come from search. Addresses are extracted deterministically (mailto, entities, Cloudflare protection, [at] spelling), one",
    "// Flash-Lite call says who owns each and who is on the team pages, and a proof check keeps only what the evidence shows.",
    "// Tiers: 1 named person, 2 department, 3 general inbox. Public addresses stay PUBLICLY LISTED, never 'verified'.",
    "// Email-first checklist (final amendment, 8 Oct): official pages, documents and media kits, people sources (speaker pages, interviews,",
    "// credits), sector directories and trade press, Instagram. Every pass records what it checked (email_research.checked, version 2):",
    "// that record is the evidence a LinkedIn fallback carries. Never contacts anyone; no Hunter. Generated by n8n/build_w23.py from n8n/w23/*.js.",
    "",
    "const manualRun = trigger({ type: 'n8n-nodes-base.manualTrigger', version: 1, config: { name: 'Manual Run' } });",
    "const schedule = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.2, config: { name: 'Daily 03:15 / 09:45 / 12:15 / 15:45 / 18:15 / 23:15 Cairo', parameters: { rule: { interval: [",
    "  { field: 'cronExpression', expression: '15 3,12,18,23 * * *' }, { field: 'cronExpression', expression: '45 9,15 * * *' }] } } } });",
    rpc('budget', 'AI Budget Check', 'ai_budget_status', '{{ "{}" }}'),
    is_true('budgetOk', 'Budget OK?', '["OK", "OVER_TARGET"].includes($json.status)'),
    rpc('queue', 'Email Gap Queue', 'email_gap_queue', '{{ JSON.stringify({ p_limit: 12 }) }}'),
    code('buildSearches', 'Build Searches', 'bs'),
    "const serper = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'Serper Search', onError: 'continueRegularOutput', alwaysOutputData: true,",
    "  parameters: { method: 'POST', url: 'https://google.serper.dev/search', authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth',",
    "    sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: expr('{{ JSON.stringify({ q: $json.q, num: 10 }) }}'),",
    "    options: { batching: { batch: { batchSize: 3, batchInterval: 1000 } } } },",
    "  credentials: { httpHeaderAuth: { id: 'RKkb2wH06uyYl3Zi', name: 'Noya Serper v2' } } } });",
    code('planPages', 'Plan Pages', 'pp'),
    "const fetchPage = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'Read Page', onError: 'continueRegularOutput', alwaysOutputData: true,",
    "  parameters: { method: 'GET', url: expr('{{ $json.url }}'), sendHeaders: true, headerParameters: { parameters: [",
    "      { name: 'User-Agent', value: 'Mozilla/5.0 (compatible; NOYA-research/1.0; +https://noyaconcierge.com)' }, { name: 'Accept', value: 'text/html,application/xhtml+xml' }] },",
    "    options: { timeout: 12000, response: { response: { responseFormat: 'text', fullResponse: true, neverError: true } },",
    "      redirect: { redirect: { followRedirects: true, maxRedirects: 4 } }, batching: { batch: { batchSize: 5, batchInterval: 300 } } } } } });",
    code('extractEvidence', 'Extract Evidence', 'ee'),
    is_true('hasEvidence', 'Has Evidence?', '$json.has_evidence'),
    "const attribute = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'Attribute (Flash-Lite)', onError: 'continueRegularOutput', retryOnFail: true, maxTries: 2, waitBetweenTries: 5000,",
    "  parameters: { method: 'POST', url: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent',",
    "    authentication: 'predefinedCredentialType', nodeCredentialType: 'googlePalmApi', sendBody: true, contentType: 'json', specifyBody: 'json',",
    "    jsonBody: expr('{{ JSON.stringify($json.request) }}'), options: { timeout: 30000, batching: { batch: { batchSize: 1, batchInterval: 4000 } } } },",
    "  credentials: { googlePalmApi: { id: 'tqsVAbFrBUJsN3Y0', name: 'Google Gemini(PaLM) Api account' } } } });",
    code('verify', 'Proof Check', 'vf'),
    code('noEvidence', 'No Evidence', 'ne'),
    rpc('save', 'Save Email Routes', 'email_intel_save', '{{ JSON.stringify({ p: $json.p }) }}', " onError: 'continueRegularOutput',"),
    "",
    "export default workflow('noya-23-email-intelligence', '23 - NOYA Email Intelligence v1')",
    "  .add(manualRun)",
    "  .to(budget)",
    "  .add(schedule)",
    "  .to(budget)",
    "  .add(budget)",
    "  .to(budgetOk.onTrue(queue.to(buildSearches.to(serper.to(planPages.to(fetchPage.to(extractEvidence.to(hasEvidence",
    "    .onTrue(attribute.to(verify.to(save)))",
    "    .onFalse(noEvidence.to(save))))))))));",
    "",
])
(H / 'workflow_23_email_intelligence.js').write_text(SRC)
print('wrote', len(SRC), 'chars')
