#!/usr/bin/env python3
"""Generate workflow 24 (Email Verification) as a Workflow SDK source from n8n/w24/*.js.
Every node is emitted inline (the SDK rejects helper function declarations)."""
import json
import pathlib

H = pathlib.Path(__file__).parent
SUPABASE = 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/'
SB = "{ supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } }"
HUNTER = "{ httpHeaderAuth: { id: 'YHdTNsj1iDDURbA7', name: 'NOYA Hunter v2' } }"


def read(p):
    return (H / p).read_text()


def rpc(var, name, fn, body):
    return (f"const {var} = node({{ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: {{ name: {json.dumps(name)}, retryOnFail: true, maxTries: 3, waitBetweenTries: 2000,\n"
            f"  parameters: {{ method: 'POST', url: '{SUPABASE}{fn}', authentication: 'predefinedCredentialType', nodeCredentialType: 'supabaseApi',\n"
            f"    sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: expr({json.dumps(body)}), options: {{ timeout: 60000 }} }},\n"
            f"  credentials: {SB} }} }});")


def code(var, name, src):
    return f"const {var} = node({{ type: 'n8n-nodes-base.code', version: 2, config: {{ name: {json.dumps(name)}, parameters: {{ mode: 'runOnceForAllItems', jsCode: {json.dumps(src)} }} }} }});"


parts = ["import { workflow, node, trigger, ifElse, expr } from '@n8n/workflow-sdk';\n",
"""// 24 - NOYA Email Verification (Adam, 8 Oct 2026: PUBLIC EMAIL -> SMTP VERIFICATION -> EMAIL READY).
// Twice a day, before the daily drafter: reads the live Hunter account, then verifies the most valuable publicly listed
// addresses with Hunter's Email Verifier, inside the daily cap and credit reserve in system_config 'email_verification'.
// valid -> VERIFIED (EMAIL READY possible); accept_all / webmail -> RISKY; invalid / disposable -> INVALID; unknown -> unchanged.
// Never buys credits, never changes the plan, never contacts anyone. Generated by n8n/build_w24.py from n8n/w24/*.js.
""",
"const manualRun = trigger({ type: 'n8n-nodes-base.manualTrigger', version: 1, config: { name: 'Manual Run' } });",
"const schedule = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.2, config: { name: 'Daily 08:40 / 20:40 Cairo', parameters: { rule: { interval: [{ field: 'cronExpression', expression: '40 8,20 * * *' }] } } } });",
f"""const account = node({{ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: {{ name: 'Hunter Account',
  parameters: {{ method: 'GET', url: 'https://api.hunter.io/v2/account', authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth',
    options: {{ timeout: 20000, response: {{ response: {{ neverError: true, fullResponse: true }} }} }} }},
  credentials: {HUNTER} }} }});""",
code('planRun', 'Plan Run', read('w24/plan_run.js')),
rpc('saveAccount', 'Save Hunter Account', 'hunter_account_save', "{{ JSON.stringify({ p: $json.account }) }}"),
rpc('queue', 'Verification Queue', 'email_verification_queue', "{{ JSON.stringify({ p_limit: 25 }) }}"),
code('splitQueue', 'Split Queue', read('w24/split_queue.js')),
f"""const verify = node({{ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: {{ name: 'Hunter Verify',
  parameters: {{ method: 'GET', url: expr("{{{{ 'https://api.hunter.io/v2/email-verifier?email=' + encodeURIComponent($json.email) }}}}"),
    authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth',
    options: {{ timeout: 30000, batching: {{ batch: {{ batchSize: 1, batchInterval: 1500 }} }}, response: {{ response: {{ neverError: true, fullResponse: true }} }} }} }},
  credentials: {HUNTER} }} }});""",
code('mapResult', 'Map Result', read('w24/map_result.js')),
rpc('save', 'Save Verification', 'email_verification_save', "{{ JSON.stringify({ p: $json.p }) }}"),
"""
export default workflow('noya-24-email-verification', '24 - NOYA Email Verification v1')
  .add(manualRun)
  .to(account)
  .add(schedule)
  .to(account)
  .add(account)
  .to(planRun.to(saveAccount.to(queue.to(splitQueue.to(verify.to(mapResult.to(save)))))));
"""]
(H / 'workflow_24_email_verification.js').write_text('\n'.join(parts))
print('ok')
