#!/usr/bin/env python3
"""Generate workflows 20 (draft revalidation), 21 (creative concepts) and 22 (Serper balance) as Workflow SDK sources.
Every node is emitted inline (the SDK rejects helper function declarations)."""
import json
import pathlib

H = pathlib.Path(__file__).parent
SUPABASE = 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/'
SB = "{ supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } }"
SERPER = "{ httpHeaderAuth: { id: 'RKkb2wH06uyYl3Zi', name: 'Noya Serper v2' } }"
GEMINI = "{ googlePalmApi: { id: 'tqsVAbFrBUJsN3Y0', name: 'Google Gemini(PaLM) Api account' } }"


def read(p):
    return (H / p).read_text()


def rpc(var, name, fn, body, extra=''):
    return (f"const {var} = node({{ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: {{ name: {json.dumps(name)}, retryOnFail: true, maxTries: 3, waitBetweenTries: 2000,{extra}\n"
            f"  parameters: {{ method: 'POST', url: '{SUPABASE}{fn}', authentication: 'predefinedCredentialType', nodeCredentialType: 'supabaseApi',\n"
            f"    sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: expr({json.dumps(body)}), options: {{ timeout: 60000 }} }},\n"
            f"  credentials: {SB} }} }});")


def code(var, name, src):
    return f"const {var} = node({{ type: 'n8n-nodes-base.code', version: 2, config: {{ name: {json.dumps(name)}, parameters: {{ mode: 'runOnceForAllItems', jsCode: {json.dumps(src)} }} }} }});"


def is_true(var, name, field):
    return (f"const {var} = ifElse({{ version: 2.2, config: {{ name: {json.dumps(name)}, parameters: {{ conditions: {{ options: {{ caseSensitive: true, leftValue: '', typeValidation: 'loose' }},\n"
            f"  conditions: [{{ leftValue: expr({json.dumps('{{ ' + field + ' }}')}), operator: {{ type: 'boolean', operation: 'true', singleValue: true }} }}], combinator: 'and' }} }} }} }});")


def schedule(var, name, cron):
    return f"const {var} = trigger({{ type: 'n8n-nodes-base.scheduleTrigger', version: 1.2, config: {{ name: {json.dumps(name)}, parameters: {{ rule: {{ interval: [{{ field: 'cronExpression', expression: {json.dumps(cron)} }}] }} }} }} }});"


MANUAL = "const manualRun = trigger({ type: 'n8n-nodes-base.manualTrigger', version: 1, config: { name: 'Manual Run' } });"
HEAD = "import { workflow, node, trigger, ifElse, expr } from '@n8n/workflow-sdk';\n"

W20 = "\n".join([
    HEAD,
    "// 20 - NOYA Draft Revalidation (Adam, 7 Oct 2026). Ready drafts older than 14 days are revalidated, never blindly redrafted:",
    "// company still qualified, still cold, no new Gmail, no newer duplicate (revalidation_queue), why-now date not passed, and one",
    "// LinkedIn search confirming the person still holds the role. revalidation_save keeps, closes, re-searches the person or frees",
    "// the account for a fresh draft. Never contacts anyone. Generated by n8n/build_w20_22.py.",
    "",
    MANUAL,
    schedule('schedule', 'Daily 10:15 Cairo', '15 10 * * *'),
    rpc('queue', 'Revalidation Queue', 'revalidation_queue', '{{ JSON.stringify({ p_limit: 15 }) }}'),
    code('checks', 'Build Checks', read('w20/build_checks.js')),
    is_true('hasName', 'Has Name?', '$json.has_name'),
    "const serper = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'Serper Search', onError: 'continueRegularOutput', alwaysOutputData: true,",
    "  parameters: { method: 'POST', url: 'https://google.serper.dev/search', authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth',",
    "    sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: expr('{{ JSON.stringify({ q: $json.q, num: 10 }) }}'),",
    "    options: { batching: { batch: { batchSize: 2, batchInterval: 1500 } } } },",
    f"  credentials: {SERPER} }} }});",
    code('verifyRole', 'Verify Role', read('w20/verify_role.js')),
    code('noName', 'Not Searchable', read('w20/no_name.js')),
    rpc('save', 'Save Revalidation', 'revalidation_save', '{{ JSON.stringify({ p: $json }) }}', " onError: 'continueRegularOutput',"),
    "",
    "export default workflow('noya-20-draft-revalidation', '20 - NOYA Draft Revalidation v1')",
    "  .add(manualRun)",
    "  .to(queue)",
    "  .add(schedule)",
    "  .to(queue)",
    "  .add(queue)",
    "  .to(checks.to(hasName",
    "    .onTrue(serper.to(verifyRole.to(save)))",
    "    .onFalse(noName.to(save))));",
    "",
])

W21 = "\n".join([
    HEAD,
    "// 21 - NOYA Creative Concepts (Adam, 7 Oct 2026). For media, podcast, YouTube, publication, creator and production targets:",
    "// CONCEPT (what could be filmed), BACKDROP (Pyramids, Mena House, Grand Egyptian Museum, Nile, Aswan, El Gouna, Red Sea, desert,",
    "// villas), NOYA ROLE and COMMERCIAL VALUE, from the stored evidence only. One Flash-Lite call per target, deterministic check,",
    "// budget guardrail first. The planner adds the concept to the draft angle. Generated by n8n/build_w20_22.py.",
    "",
    MANUAL,
    schedule('schedule', 'Daily 11:30 Cairo', '30 11 * * *'),
    rpc('budget', 'AI Budget Check', 'ai_budget_status', '{{ "{}" }}'),
    is_true('budgetOk', 'Budget OK?', '["OK", "OVER_TARGET"].includes($json.status)'),
    rpc('queue', 'Concept Queue', 'creative_concept_queue', '{{ JSON.stringify({ p_limit: 8 }) }}'),
    code('prompts', 'Build Prompts', read('w21/build_prompts.js')),
    "const gemini = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'Flash-Lite Concept', onError: 'continueRegularOutput', retryOnFail: true, maxTries: 2, waitBetweenTries: 5000,",
    "  parameters: { method: 'POST', url: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent',",
    "    authentication: 'predefinedCredentialType', nodeCredentialType: 'googlePalmApi', sendBody: true, contentType: 'json', specifyBody: 'json',",
    "    jsonBody: expr('{{ JSON.stringify($json.request) }}'), options: { timeout: 30000, batching: { batch: { batchSize: 1, batchInterval: 4000 } } } },",
    f"  credentials: {GEMINI} }} }});",
    code('verify', 'Verify Concept', read('w21/verify.js')),
    rpc('save', 'Save Concept', 'creative_concept_save', '{{ JSON.stringify({ p: $json.p }) }}', " onError: 'continueRegularOutput',"),
    "",
    "export default workflow('noya-21-creative-concepts', '21 - NOYA Creative Concepts v1')",
    "  .add(manualRun)",
    "  .to(budget)",
    "  .add(schedule)",
    "  .to(budget)",
    "  .add(budget)",
    "  .to(budgetOk.onTrue(queue.to(prompts.to(gemini.to(verify.to(save))))));",
    "",
])

W22 = "\n".join([
    HEAD,
    "// 22 - NOYA Serper Balance (Adam, 7 Oct 2026: check the real allowance). Reads the Serper account balance every 6 hours",
    "// (no search credit spent) and stores it, so serper_usage() reports measured burn per day and per 3-day cycle.",
    "// Generated by n8n/build_w20_22.py.",
    "",
    MANUAL,
    schedule('schedule', 'Every 6 hours', '5 */6 * * *'),
    "const account = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'Serper Account', retryOnFail: true, maxTries: 3, waitBetweenTries: 5000,",
    "  parameters: { method: 'GET', url: 'https://google.serper.dev/account', authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth', options: { timeout: 20000 } },",
    f"  credentials: {SERPER} }} }});",
    rpc('save', 'Save Balance', 'provider_balance_save', '{{ JSON.stringify({ p_provider: "SERPER", p_balance: $json.balance, p_rate_limit: $json.rateLimit }) }}'),
    "",
    "export default workflow('noya-22-serper-balance', '22 - NOYA Serper Balance v1')",
    "  .add(manualRun)",
    "  .to(account)",
    "  .add(schedule)",
    "  .to(account)",
    "  .add(account)",
    "  .to(save);",
    "",
])

for fname, src in [('workflow_20_draft_revalidation.js', W20), ('workflow_21_creative_concepts.js', W21), ('workflow_22_serper_balance.js', W22)]:
    (H / fname).write_text(src)
    print('wrote', fname, len(src))
