#!/usr/bin/env python3
"""Generate n8n/workflow_19_contact_enrichment.js (Workflow SDK) from the code files in n8n/w19/.

The SDK rejects helper function declarations, so every node is emitted inline here.
Usage: python3 n8n/build_w19.py   (then update the live workflow with the n8n MCP tools)
"""
import json
import pathlib

H = pathlib.Path(__file__).parent
CODE = {k: (H / 'w19' / f).read_text() for k, f in [('bq', 'build_queries.js'), ('gr', 'group_results.js'), ('vf', 'verify.js'), ('nr', 'no_results.js')]}
SUPABASE = 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/'
SUPABASE_CRED = "{ supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } }"


def rpc(var, name, fn, body, extra=''):
    return (f"const {var} = node({{ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: {{ name: {json.dumps(name)}, retryOnFail: true, maxTries: 3, waitBetweenTries: 2000,{extra}\n"
            f"  parameters: {{ method: 'POST', url: '{SUPABASE}{fn}', authentication: 'predefinedCredentialType', nodeCredentialType: 'supabaseApi',\n"
            f"    sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: expr({json.dumps(body)}), options: {{ timeout: 60000 }} }},\n"
            f"  credentials: {SUPABASE_CRED} }} }});")


def code(var, name, key):
    return f"const {var} = node({{ type: 'n8n-nodes-base.code', version: 2, config: {{ name: {json.dumps(name)}, parameters: {{ mode: 'runOnceForAllItems', jsCode: {json.dumps(CODE[key])} }} }} }});"


def is_true(var, name, field):
    return (f"const {var} = ifElse({{ version: 2.2, config: {{ name: {json.dumps(name)}, parameters: {{ conditions: {{ options: {{ caseSensitive: true, leftValue: '', typeValidation: 'loose' }},\n"
            f"  conditions: [{{ leftValue: expr({json.dumps('{{ ' + field + ' }}')}), operator: {{ type: 'boolean', operation: 'true', singleValue: true }} }}], combinator: 'and' }} }} }} }});")


SRC = "\n".join([
    "import { workflow, node, trigger, ifElse, expr } from '@n8n/workflow-sdk';",
    "",
    "// 19 - NOYA Contact Route Enrichment (Adam, 7 Oct 2026). Finds the actual route into each prospect:",
    "// named decision maker + published business email, then LinkedIn, then Instagram, then the right company inbox.",
    "// Serper search (3 queries per company) -> one Flash-Lite extraction -> deterministic anti-fabrication check",
    "// (every name, email and handle must appear verbatim in the cited result; roles that are not a route in are dropped;",
    "// a LinkedIn profile that names the company only outside its headline stays unconfirmed; at most 4 people per company)",
    "// -> enrich_company_routes (dedupes, fills gaps, keeps source URL and type; public emails stay UNVERIFIED).",
    "// Hunter is never called. Never contacts anyone. Generated by n8n/build_w19.py from n8n/w19/*.js.",
    "",
    "const manualRun = trigger({ type: 'n8n-nodes-base.manualTrigger', version: 1, config: { name: 'Manual Run' } });",
    "const schedule = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.2, config: { name: 'Daily 11:00 / 17:00 / 21:00 Cairo', parameters: { rule: { interval: [{ field: 'cronExpression', expression: '0 11,17,21 * * *' }] } } } });",
    rpc('budget', 'AI Budget Check', 'ai_budget_status', '{{ "{}" }}'),
    is_true('budgetOk', 'Budget OK?', '["OK", "OVER_TARGET"].includes($json.status)'),
    rpc('queue', 'Enrichment Queue', 'enrichment_queue', '{{ JSON.stringify({ p_limit: 12 }) }}'),
    code('buildQueries', 'Build Queries', 'bq'),
    "const serper = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'Serper Search', onError: 'continueRegularOutput', alwaysOutputData: true,",
    "  parameters: { method: 'POST', url: 'https://google.serper.dev/search', authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth',",
    "    sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: expr('{{ JSON.stringify({ q: $json.q, num: 10 }) }}'),",
    "    options: { batching: { batch: { batchSize: 2, batchInterval: 1500 } } } },",
    "  credentials: { httpHeaderAuth: { id: 'RKkb2wH06uyYl3Zi', name: 'Noya Serper v2' } } } });",
    code('group', 'Group Results', 'gr'),
    is_true('hasResults', 'Has Results?', '$json.has_results'),
    "const extract = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'Extract Routes (Flash-Lite)', onError: 'continueRegularOutput', retryOnFail: true, maxTries: 2, waitBetweenTries: 5000,",
    "  parameters: { method: 'POST', url: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent',",
    "    authentication: 'predefinedCredentialType', nodeCredentialType: 'googlePalmApi', sendBody: true, contentType: 'json', specifyBody: 'json',",
    "    jsonBody: expr('{{ JSON.stringify($json.request) }}'), options: { timeout: 30000, batching: { batch: { batchSize: 1, batchInterval: 4000 } } } },",
    "  credentials: { googlePalmApi: { id: 'tqsVAbFrBUJsN3Y0', name: 'Google Gemini(PaLM) Api account' } } } });",
    code('verify', 'Verify Against Evidence', 'vf'),
    code('noResults', 'No Results', 'nr'),
    # one company failing to save must not stop the others
    rpc('save', 'Save Routes', 'enrich_company_routes', '{{ JSON.stringify({ p: $json.p }) }}', " onError: 'continueRegularOutput',"),
    "",
    "export default workflow('noya-19-contact-enrichment', '19 - NOYA Contact Route Enrichment v1')",
    "  .add(manualRun)",
    "  .to(budget)",
    "  .add(schedule)",
    "  .to(budget)",
    "  .add(budget)",
    "  .to(budgetOk.onTrue(queue.to(buildQueries.to(serper.to(group.to(hasResults",
    "    .onTrue(extract.to(verify.to(save)))",
    "    .onFalse(noResults.to(save))))))));",
    "",
])
(H / 'workflow_19_contact_enrichment.js').write_text(SRC)
print('wrote', len(SRC), 'chars')
