#!/usr/bin/env python3
"""Generate workflow 25 (Email Finder) as a Workflow SDK source from n8n/w25/*.js."""
import json
import pathlib

H = pathlib.Path(__file__).parent
SUPABASE = 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/'
SB = "{ supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } }"
HUNTER = "{ httpHeaderAuth: { id: 'YHdTNsj1iDDURbA7', name: 'NOYA Hunter v2' } }"


def read(p):
    return (H / p).read_text()


def rpc(var, name, fn, body):
    return (f"const {var} = node({{ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: {{ name: {json.dumps(name)}, retryOnFail: true, maxTries: 3, waitBetweenTries: 2000,\n"
            f"  parameters: {{ method: 'POST', url: '{SUPABASE}{fn}', authentication: 'predefinedCredentialType', nodeCredentialType: 'supabaseApi',\n"
            f"    sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: expr({json.dumps(body)}), options: {{ timeout: 60000 }} }},\n"
            f"  credentials: {SB} }} }});")


def code(var, name, src):
    return f"const {var} = node({{ type: 'n8n-nodes-base.code', version: 2, config: {{ name: {json.dumps(name)}, parameters: {{ mode: 'runOnceForAllItems', jsCode: {json.dumps(src)} }} }} }});"


parts = ["import { workflow, node, trigger, expr } from '@n8n/workflow-sdk';\n",
"""// 25 - NOYA Email Finder (Adam, 8 Oct 2026 — email-first amendment). The provider step, used only after the company and the
// right person are established and public email research is exhausted (email_finder_queue: route state EXHAUSTED, no address
// for the person, trusted company domain). Hunter's Email Finder looks the person up by name + domain; the address is saved
// only when Hunter verifies it valid on that domain. Runs after verification (20:40) so verification keeps first use of the
// credits; keeps a credit reserve; never buys credits, never contacts anyone. Generated by n8n/build_w25.py from n8n/w25/*.js.
""",
"const manualRun = trigger({ type: 'n8n-nodes-base.manualTrigger', version: 1, config: { name: 'Manual Run' } });",
"const schedule = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.2, config: { name: 'Daily 20:55 Cairo', parameters: { rule: { interval: [{ field: 'cronExpression', expression: '55 20 * * *' }] } } } });",
f"""const account = node({{ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: {{ name: 'Hunter Account',
  parameters: {{ method: 'GET', url: 'https://api.hunter.io/v2/account', authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth',
    options: {{ timeout: 20000, response: {{ response: {{ neverError: true, fullResponse: true }} }} }} }},
  credentials: {HUNTER} }} }});""",
code('planRun', 'Plan Run', read('w25/plan_run.js')),
rpc('queue', 'Finder Queue', 'email_finder_queue', "{{ JSON.stringify({ p_limit: 5 }) }}"),
code('splitQueue', 'Split Queue', read('w25/split_queue.js')),
f"""const finder = node({{ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: {{ name: 'Hunter Email Finder',
  parameters: {{ method: 'GET', url: expr("{{{{ 'https://api.hunter.io/v2/email-finder?domain=' + encodeURIComponent($json.domain) + '&first_name=' + encodeURIComponent($json.first_name) + '&last_name=' + encodeURIComponent($json.last_name) }}}}"),
    authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth',
    options: {{ timeout: 30000, batching: {{ batch: {{ batchSize: 1, batchInterval: 1500 }} }}, response: {{ response: {{ neverError: true, fullResponse: true }} }} }} }},
  credentials: {HUNTER} }} }});""",
code('mapResult', 'Map Result', read('w25/map_result.js')),
rpc('save', 'Save Finder Result', 'email_finder_save', "{{ JSON.stringify({ p: $json.p }) }}"),
"""
export default workflow('noya-25-email-finder', '25 - NOYA Email Finder v1')
  .add(manualRun)
  .to(account)
  .add(schedule)
  .to(account)
  .add(account)
  .to(planRun.to(queue.to(splitQueue.to(finder.to(mapResult.to(save))))));
"""]
(H / 'workflow_25_email_finder.js').write_text('\n'.join(parts))
print('ok')
