SUPA = "https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/"
SC = "{ supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } }"
GC = "{ gmailOAuth2: { id: 'OMGm2CkcvDKbJTr3', name: 'NOYA Gmail' } }"
def rpc(var, fn, name, body, pos):
    return f"""const {var} = node({{
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {{
    name: '{name}',
    position: {pos},
    parameters: {{
      method: 'POST',
      url: '{SUPA}{fn}',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: {body},
      options: {{ timeout: 20000 }}
    }},
    credentials: {SC}
  }}
}});
"""
def respond(var, name, body, code, pos):
    return f"""const {var} = node({{
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: {{ name: '{name}', position: {pos}, parameters: {{ respondWith: 'json', responseBody: {body}, options: {{ responseCode: {code} }} }} }}
}});
"""
OID = "$('Validate Outbound Id').first().json.outbound_id"
out = []
out.append("""import { workflow, node, trigger, ifElse, expr } from '@n8n/workflow-sdk';

// 12 - NOYA Outbound Email Executor v1
// Executes exactly one Adam-approved outbound_emails row. The webhook accepts only an
// outbound id; recipient, subject and body always come from the database row that
// outbound_approve() created after every gate passed. No schedule, no loop, no batch:
// one call sends or drafts at most one email, from noya@noyaconcierge.com only.
// Generated by n8n/gen_12_outbound_email_executor.py - edit that file, not this one.

const webhook = trigger({
  type: 'n8n-nodes-base.webhook',
  version: 2.1,
  config: {
    name: 'Execute Approved Outbound',
    position: [0, 300],
    parameters: { httpMethod: 'POST', path: 'noya-outbound-execute', responseMode: 'responseNode', options: {} }
  }
});

const validateInput = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Validate Outbound Id',
    position: [220, 300],
    parameters: {
      mode: 'runOnceForAllItems',
      jsCode: "var body = ($input.first().json.body) || {};\\nvar id = String(body.outbound_id || '').trim();\\nif (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)) {\\n  throw new Error('outbound_id must be a uuid');\\n}\\nreturn [{ json: { outbound_id: id } }];"
    }
  }
});

// Sender identity guard: refuse to run unless the Gmail credential is the NOYA mailbox.
const verifyMailbox = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Verify NOYA Mailbox',
    position: [440, 300],
    parameters: {
      method: 'GET',
      url: 'https://gmail.googleapis.com/gmail/v1/users/me/profile',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'gmailOAuth2',
      options: { timeout: 20000 }
    },
    credentials: """ + GC + """
  }
});

const mailboxIsNoya = ifElse({
  version: 2.2,
  config: {
    name: 'Mailbox Is NOYA?',
    position: [660, 300],
    parameters: {
      conditions: {
        options: { caseSensitive: false, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: expr('{{ $json.emailAddress }}'), operator: { type: 'string', operation: 'equals' }, rightValue: 'noya@noyaconcierge.com' }],
        combinator: 'and'
      }
    }
  }
});

const claimed = ifElse({
  version: 2.2,
  config: {
    name: 'Claimed?',
    position: [1100, 200],
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: expr('{{ $json.ok }}'), operator: { type: 'boolean', operation: 'true', singleValue: true }, rightValue: '' }],
        combinator: 'and'
      }
    }
  }
});

const isSend = ifElse({
  version: 2.2,
  config: {
    name: 'Explicit Send?',
    position: [1320, 100],
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'strict' },
        conditions: [{ leftValue: expr('{{ $json.mode }}'), operator: { type: 'string', operation: 'equals' }, rightValue: 'SEND' }],
        combinator: 'and'
      }
    }
  }
});

const gmailSend = node({
  type: 'n8n-nodes-base.gmail',
  version: 2.2,
  config: {
    name: 'Gmail Send (noya@)',
    position: [1540, 0],
    onError: 'continueErrorOutput',
    parameters: {
      resource: 'message',
      operation: 'send',
      sendTo: expr('{{ $json.to_email }}'),
      subject: expr('{{ $json.subject }}'),
      emailType: 'text',
      message: expr('{{ $json.body }}'),
      options: { appendAttribution: false }
    },
    credentials: """ + GC + """
  }
});

const gmailDraft = node({
  type: 'n8n-nodes-base.gmail',
  version: 2.2,
  config: {
    name: 'Gmail Create Draft (noya@)',
    position: [1540, 200],
    onError: 'continueErrorOutput',
    parameters: {
      resource: 'draft',
      operation: 'create',
      subject: expr('{{ $json.subject }}'),
      emailType: 'text',
      message: expr('{{ $json.body }}'),
      options: { sendTo: expr('{{ $json.to_email }}') }
    },
    credentials: """ + GC + """
  }
});
""")
q = lambda s: "expr(" + repr("{{ " + s + " }}") + ")"
out.append(rpc("claim", "outbound_claim", "Claim Outbound (exactly once)", q(f"JSON.stringify({{ p_outbound_id: {OID} }})"), "[880, 200]"))
out.append(rpc("completeSend", "outbound_complete", "Record Send In CRM", q(f"JSON.stringify({{ p_outbound_id: {OID}, p_gmail_message_id: $json.id, p_gmail_thread_id: $json.threadId, p_gmail_draft_id: null }})"), "[1760, -60]"))
out.append(rpc("completeDraft", "outbound_complete", "Record Draft In CRM", q(f"JSON.stringify({{ p_outbound_id: {OID}, p_gmail_message_id: $json.message.id, p_gmail_thread_id: $json.message.threadId, p_gmail_draft_id: $json.id }})"), "[1760, 180]"))
out.append(rpc("failSend", "outbound_fail", "Record Send Failure", q(f"JSON.stringify({{ p_outbound_id: {OID}, p_error: String(($json.error && ($json.error.message || $json.error)) || 'gmail send failed') }})"), "[1760, 60]"))
out.append(rpc("failDraft", "outbound_fail", "Record Draft Failure", q(f"JSON.stringify({{ p_outbound_id: {OID}, p_error: String(($json.error && ($json.error.message || $json.error)) || 'gmail draft failed') }})"), "[1760, 300]"))
out.append(respond("respondDone", "Respond Result", q("JSON.stringify($json)"), 200, "[1980, 60]"))
out.append(respond("respondDoneDraft", "Respond Draft Result", q("JSON.stringify($json)"), 200, "[1980, 240]"))
out.append(respond("respondFailed", "Respond Failure", q("JSON.stringify({ ok: false, reason: 'PROVIDER_ERROR', detail: $json })"), 502, "[1980, 150]"))
out.append(respond("respondFailedDraft", "Respond Draft Failure", q("JSON.stringify({ ok: false, reason: 'PROVIDER_ERROR', detail: $json })"), 502, "[1980, 330]"))
out.append(respond("respondNotClaimed", "Respond Not Claimed", q("JSON.stringify($json)"), 409, "[1320, 320]"))
out.append(respond("respondWrongMailbox", "Respond Wrong Mailbox", q("JSON.stringify({ ok: false, reason: 'WRONG_MAILBOX', mailbox: $json.emailAddress })"), 500, "[880, 420]"))
out.append("""
export default workflow('noya-12-outbound-executor', '12 - NOYA Outbound Email Executor v1')
  .add(webhook)
  .to(validateInput)
  .to(verifyMailbox)
  .to(mailboxIsNoya
    .onTrue(claim.to(claimed
      .onTrue(isSend
        .onTrue(gmailSend
          .onError(failSend.to(respondFailed))
          .to(completeSend.to(respondDone)))
        .onFalse(gmailDraft
          .onError(failDraft.to(respondFailedDraft))
          .to(completeDraft.to(respondDoneDraft))))
      .onFalse(respondNotClaimed)))
    .onFalse(respondWrongMailbox));
""")
open("n8n/12_outbound_email_executor.workflow.ts","w").write("\n".join(out))
