import { workflow, node, trigger, expr } from '@n8n/workflow-sdk';

// 25 - NOYA Email Finder (Adam, 8 Oct 2026 — email-first amendment). The provider step, used only after the company and the
// right person are established and public email research is exhausted (email_finder_queue: route state EXHAUSTED, no address
// for the person, trusted company domain). Hunter's Email Finder looks the person up by name + domain; the address is saved
// only when Hunter verifies it valid on that domain. Runs after verification (20:40) so verification keeps first use of the
// credits; keeps a credit reserve; never buys credits, never contacts anyone. Generated by n8n/build_w25.py from n8n/w25/*.js.

const manualRun = trigger({ type: 'n8n-nodes-base.manualTrigger', version: 1, config: { name: 'Manual Run' } });
const schedule = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.2, config: { name: 'Daily 20:55 Cairo', parameters: { rule: { interval: [{ field: 'cronExpression', expression: '55 20 * * *' }] } } } });
const account = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'Hunter Account',
  parameters: { method: 'GET', url: 'https://api.hunter.io/v2/account', authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth',
    options: { timeout: 20000, response: { response: { neverError: true, fullResponse: true } } } },
  credentials: { httpHeaderAuth: { id: 'YHdTNsj1iDDURbA7', name: 'NOYA Hunter v2' } } } });
const planRun = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: "Plan Run", parameters: { mode: 'runOnceForAllItems', jsCode: "// Live Hunter account -> how many Email Finder lookups this run may use (one credit each). Nothing is bought.\nvar r = $input.first().json || {};\nvar code = Number(r.statusCode || 0);\nvar d = (r.body && r.body.data) || {};\nvar req = d.requests || {};\nfunction left(x) { return x && x.available != null ? Math.max(0, Number(x.available) - Number(x.used || 0)) : null; }\nvar cred = left(req.credits), srch = left(req.searches);\nvar room = cred == null ? (srch == null ? 0 : srch) : cred;\nif (srch != null) room = Math.min(room, srch);\nvar ok = code >= 200 && code < 300 && !!d.plan_name;\nreturn [{ json: { ok: ok, room: ok ? room : 0, plan: d.plan_name || null, http_status: code } }];\n" } } });
const queue = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: "Finder Queue", retryOnFail: true, maxTries: 3, waitBetweenTries: 2000,
  parameters: { method: 'POST', url: 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/email_finder_queue', authentication: 'predefinedCredentialType', nodeCredentialType: 'supabaseApi',
    sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: expr("{{ JSON.stringify({ p_limit: 5 }) }}"), options: { timeout: 60000 } },
  credentials: { supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } } } });
const splitQueue = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: "Split Queue", parameters: { mode: 'runOnceForAllItems', jsCode: "// The queue applies the daily finder cap; the live credits and the reserve (kept for verification) can only shorten it.\nvar q = $input.first().json || {};\nvar plan = $('Plan Run').first().json;\nvar n = Math.max(0, Math.min((q.items || []).length, plan.room - Number(q.reserve_credits || 0)));\nif (!plan.ok) n = 0;\nreturn (q.items || []).slice(0, n).map(function (i) { return { json: i }; });\n" } } });
const finder = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'Hunter Email Finder',
  parameters: { method: 'GET', url: expr("{{ 'https://api.hunter.io/v2/email-finder?domain=' + encodeURIComponent($json.domain) + '&first_name=' + encodeURIComponent($json.first_name) + '&last_name=' + encodeURIComponent($json.last_name) }}"),
    authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth',
    options: { timeout: 30000, batching: { batch: { batchSize: 1, batchInterval: 1500 } }, response: { response: { neverError: true, fullResponse: true } } } },
  credentials: { httpHeaderAuth: { id: 'YHdTNsj1iDDURbA7', name: 'NOYA Hunter v2' } } } });
const mapResult = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: "Map Result", parameters: { mode: 'runOnceForAllItems', jsCode: "// A definite Hunter answer is saved (found + verification status, or not found). 202 / 429 are left for the next run.\n// The database keeps a provider address only when Hunter verifies it valid on the company domain.\nvar src = $('Split Queue').all();\nvar out = [];\n$input.all().forEach(function (x, i) {\n  var it = src[i] && src[i].json; if (!it) return;\n  var r = x.json || {}; var code = Number(r.statusCode || 0); var d = (r.body && r.body.data) || {};\n  if (code === 202 || code === 429) return;\n  out.push({ json: { p: {\n    contact_id: it.contact_id, status_code: code, email: d.email || '', score: d.score,\n    verification: (d.verification && d.verification.status) || '',\n    sources: (d.sources || []).slice(0, 5).map(function (s) { return { uri: s.uri, domain: s.domain, extracted_on: s.extracted_on, still_on_page: s.still_on_page }; }),\n    execution: String($execution.id) } } });\n});\nreturn out;\n" } } });
const save = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: "Save Finder Result", retryOnFail: true, maxTries: 3, waitBetweenTries: 2000,
  parameters: { method: 'POST', url: 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/email_finder_save', authentication: 'predefinedCredentialType', nodeCredentialType: 'supabaseApi',
    sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: expr("{{ JSON.stringify({ p: $json.p }) }}"), options: { timeout: 60000 } },
  credentials: { supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } } } });

export default workflow('noya-25-email-finder', '25 - NOYA Email Finder v1')
  .add(manualRun)
  .to(account)
  .add(schedule)
  .to(account)
  .add(account)
  .to(planRun.to(queue.to(splitQueue.to(finder.to(mapResult.to(save))))));
