import { workflow, node, trigger, ifElse, expr } from '@n8n/workflow-sdk';

// 24 - NOYA Email Verification (Adam, 8 Oct 2026: PUBLIC EMAIL -> SMTP VERIFICATION -> EMAIL READY).
// Twice a day, before the daily drafter: reads the live Hunter account, then verifies the most valuable publicly listed
// addresses with Hunter's Email Verifier, inside the daily cap and credit reserve in system_config 'email_verification'.
// valid -> VERIFIED (EMAIL READY possible); accept_all / webmail -> RISKY; invalid / disposable -> INVALID; unknown -> unchanged.
// Never buys credits, never changes the plan, never contacts anyone. Generated by n8n/build_w24.py from n8n/w24/*.js.

const manualRun = trigger({ type: 'n8n-nodes-base.manualTrigger', version: 1, config: { name: 'Manual Run' } });
const schedule = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.2, config: { name: 'Daily 08:40 / 20:40 Cairo', parameters: { rule: { interval: [{ field: 'cronExpression', expression: '40 8,20 * * *' }] } } } });
const account = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'Hunter Account',
  parameters: { method: 'GET', url: 'https://api.hunter.io/v2/account', authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth',
    options: { timeout: 20000, response: { response: { neverError: true, fullResponse: true } } } },
  credentials: { httpHeaderAuth: { id: 'YHdTNsj1iDDURbA7', name: 'NOYA Hunter v2' } } } });
const planRun = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: "Plan Run", parameters: { mode: 'runOnceForAllItems', jsCode: "// Live Hunter account -> how many verifications this run may use. Nothing is bought: if the account is short, the run is short.\nvar r = $input.first().json || {};\nvar code = Number(r.statusCode || 0);\nvar d = (r.body && r.body.data) || {};\nvar req = d.requests || {};\nfunction left(x) { return x && x.available != null ? Math.max(0, Number(x.available) - Number(x.used || 0)) : null; }\nvar ver = left(req.verifications), cred = left(req.credits);\nvar room = ver == null ? 0 : ver;\nif (cred != null) room = Math.min(room, Math.floor(cred * 2)); // a verification costs half a credit\nvar ok = code >= 200 && code < 300 && !!d.plan_name;\nvar account = {\n  ok: ok, http_status: code, plan: d.plan_name || null, reset_date: d.reset_date || null,\n  verifications_used: req.verifications ? req.verifications.used : null, verifications_available: req.verifications ? req.verifications.available : null,\n  credits_used: req.credits ? req.credits.used : null, credits_available: req.credits ? req.credits.available : null,\n  searches_used: req.searches ? req.searches.used : null, searches_available: req.searches ? req.searches.available : null,\n  verifications_left: ok ? room : null\n};\nreturn [{ json: { account: account, room: ok ? room : 0 } }];\n" } } });
const saveAccount = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: "Save Hunter Account", retryOnFail: true, maxTries: 3, waitBetweenTries: 2000,
  parameters: { method: 'POST', url: 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/hunter_account_save', authentication: 'predefinedCredentialType', nodeCredentialType: 'supabaseApi',
    sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: expr("{{ JSON.stringify({ p: $json.account }) }}"), options: { timeout: 60000 } },
  credentials: { supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } } } });
const queue = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: "Verification Queue", retryOnFail: true, maxTries: 3, waitBetweenTries: 2000,
  parameters: { method: 'POST', url: 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/email_verification_queue', authentication: 'predefinedCredentialType', nodeCredentialType: 'supabaseApi',
    sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: expr("{{ JSON.stringify({ p_limit: 25 }) }}"), options: { timeout: 60000 } },
  credentials: { supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } } } });
const splitQueue = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: "Split Queue", parameters: { mode: 'runOnceForAllItems', jsCode: "// The queue already applies the daily cap; here the live account and the reserve can only shorten it.\nvar q = $input.first().json || {};\nvar plan = $('Plan Run').first().json;\nvar reserve = Number(q.reserve_verifications || 0);\nvar n = Math.max(0, Math.min((q.items || []).length, plan.room - reserve));\nif (!q.enabled || !plan.account.ok) n = 0;\nreturn (q.items || []).slice(0, n).map(function (i) { return { json: i }; });\n" } } });
const verify = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'Hunter Verify',
  parameters: { method: 'GET', url: expr("{{ 'https://api.hunter.io/v2/email-verifier?email=' + encodeURIComponent($json.email) }}"),
    authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth',
    options: { timeout: 30000, batching: { batch: { batchSize: 1, batchInterval: 1500 } }, response: { response: { neverError: true, fullResponse: true } } } },
  credentials: { httpHeaderAuth: { id: 'YHdTNsj1iDDURbA7', name: 'NOYA Hunter v2' } } } });
const mapResult = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: "Map Result", parameters: { mode: 'runOnceForAllItems', jsCode: "// Only a definite Hunter answer is saved. 202 (still verifying), 429 and errors are left for the next run (no credit charged).\nvar src = $('Split Queue').all();\nvar out = [];\n$input.all().forEach(function (x, i) {\n  var it = src[i] && src[i].json; if (!it) return;\n  var r = x.json || {}; var code = Number(r.statusCode || 0); var d = (r.body && r.body.data) || {};\n  if (code !== 200 || !d.status) return;\n  out.push({ json: { p: {\n    contact_id: it.contact_id, email: it.email, status: d.status, result: d.result || null, score: d.score, accept_all: d.accept_all,\n    sources: (d.sources || []).slice(0, 5).map(function (s) { return { uri: s.uri, domain: s.domain, extracted_on: s.extracted_on, still_on_page: s.still_on_page }; }),\n    execution: String($execution.id) } } });\n});\nreturn out;\n" } } });
const save = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: "Save Verification", retryOnFail: true, maxTries: 3, waitBetweenTries: 2000,
  parameters: { method: 'POST', url: 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/email_verification_save', authentication: 'predefinedCredentialType', nodeCredentialType: 'supabaseApi',
    sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: expr("{{ JSON.stringify({ p: $json.p }) }}"), options: { timeout: 60000 } },
  credentials: { supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } } } });

export default workflow('noya-24-email-verification', '24 - NOYA Email Verification v1')
  .add(manualRun)
  .to(account)
  .add(schedule)
  .to(account)
  .add(account)
  .to(planRun.to(saveAccount.to(queue.to(splitQueue.to(verify.to(mapResult.to(save)))))));
