import { workflow, node, trigger, ifElse, expr } from '@n8n/workflow-sdk';

// 22 - NOYA Serper Balance (Adam, 7 Oct 2026: check the real allowance). Reads the Serper account balance every 6 hours
// (no search credit spent) and stores it, so serper_usage() reports measured burn per day and per 3-day cycle.
// Generated by n8n/build_w20_22.py.

const manualRun = trigger({ type: 'n8n-nodes-base.manualTrigger', version: 1, config: { name: 'Manual Run' } });
const schedule = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.2, config: { name: "Every 6 hours", parameters: { rule: { interval: [{ field: 'cronExpression', expression: "5 */6 * * *" }] } } } });
const account = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'Serper Account', retryOnFail: true, maxTries: 3, waitBetweenTries: 5000,
  parameters: { method: 'GET', url: 'https://google.serper.dev/account', authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth', options: { timeout: 20000 } },
  credentials: { httpHeaderAuth: { id: 'RKkb2wH06uyYl3Zi', name: 'Noya Serper v2' } } } });
const save = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: "Save Balance", retryOnFail: true, maxTries: 3, waitBetweenTries: 2000,
  parameters: { method: 'POST', url: 'https://gagbhykzmtstekpqujyl.supabase.co/rest/v1/rpc/provider_balance_save', authentication: 'predefinedCredentialType', nodeCredentialType: 'supabaseApi',
    sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: expr("{{ JSON.stringify({ p_provider: \"SERPER\", p_balance: $json.balance, p_rate_limit: $json.rateLimit }) }}"), options: { timeout: 60000 } },
  credentials: { supabaseApi: { id: 'EkLYXHBGqNUjAGKP', name: 'Supabase account' } } } });

export default workflow('noya-22-serper-balance', '22 - NOYA Serper Balance v1')
  .add(manualRun)
  .to(account)
  .add(schedule)
  .to(account)
  .add(account)
  .to(save);
