-- HOW TO RUN (one paste): Supabase dashboard -> project gagbhykzmtstekpqujyl -> SQL editor ->
-- paste this whole file -> Run once (the approvals only touch rows still VERIFIED; the audit log adds a line per run).
-- (The Supabase connector in Claude's session holds approval writes for a confirmation it
-- cannot show, so this one step is Adam's.)
-- Private Calendar launch approval (3 Oct 2026). Adam approved the launch set in writing
-- ("APPROVE V3 FINAL") on condition that every event is re-checked against its official source
-- first and that nothing with uncertain or moving dates is approved.
-- Re-check, 3 Oct 2026: 17 events confirmed on the organiser's own domain or official ticketing
-- and in independent reporting. Held: Shakira at the Pyramids of Giza (the date has already moved
-- once, 7 Apr -> 28 Nov 2026, because of the regional situation, and only the promoter's ticketing
-- confirms it): it stays VERIFIED, unapproved and off the public calendar.
-- Same steps as hq_calendar_approve (gate on, approve, gate off, audit), recorded against Adam's
-- written approval; one row per statement, by id.
begin;
set local lock_timeout = '5s';
select set_config('noya.calendar_gate', 'on', true);

update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = '1218021c-645c-454f-97b7-47ead048da24' and calendar_status = 'VERIFIED';  -- el-gouna-film-festival-2026
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = '68158dc6-7c6f-4c69-8852-8fb8e4680747' and calendar_status = 'VERIFIED';  -- abu-simbel-sun-festival-october-2026
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = '94108f87-5858-4bce-88bc-e3e7f99e8096' and calendar_status = 'VERIFIED';  -- art-basel-paris-2026
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = 'cb97d931-8365-4ac2-9787-825cde715a57' and calendar_status = 'VERIFIED';  -- forever-is-now-06
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = 'daea469f-a0d4-4597-a17f-e0f5ae3af191' and calendar_status = 'VERIFIED';  -- cairo-international-film-festival-2026
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = '6715fc0f-9aab-444d-a903-dbae300ffc5a' and calendar_status = 'VERIFIED';  -- abu-dhabi-grand-prix-2026
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = '0fab885e-40f1-4051-8a95-daf7a9fcd46f' and calendar_status = 'VERIFIED';  -- art-basel-miami-beach-2026
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = 'd58e1b5a-b98b-4509-a150-16bf6519afa9' and calendar_status = 'VERIFIED';  -- french-alps-winter-season-2026-27
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = '83446988-2383-452c-b43c-fea22e07cf7f' and calendar_status = 'VERIFIED';  -- haute-couture-week-spring-summer-2027
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = '7b4b8a7c-9993-48f3-a04c-f0bd6c5ac298' and calendar_status = 'VERIFIED';  -- abu-simbel-sun-festival-february-2027
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = 'd38acc1a-ef0d-4ee7-aab5-a31dc3e63a9a' and calendar_status = 'VERIFIED';  -- paris-fashion-week-womenswear-fall-winter-2027
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = '7ce682ca-05ea-419f-98a9-9e2e6baafb27' and calendar_status = 'VERIFIED';  -- dubai-world-cup-2027
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = 'c3dfd10f-1101-4e8a-95e5-8cbc75a2fb48' and calendar_status = 'VERIFIED';  -- festival-de-cannes-2027
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = '8981a114-436e-41e8-a5c6-d77099aa5050' and calendar_status = 'VERIFIED';  -- monaco-grand-prix-2027
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = '046b1f38-d372-473d-a6d5-58f517c9bb85' and calendar_status = 'VERIFIED';  -- uefa-champions-league-final-2027
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = '6582907f-7b16-44f7-aeb1-3da95042764a' and calendar_status = 'VERIFIED';  -- royal-ascot-2027
update public.intelligence set calendar_status = 'APPROVED', approved_by = 'Adam Elshazly (APPROVE V3 FINAL, 3 Oct 2026)', approved_at = now(), notes = 'Dates re-checked on 3 Oct 2026 against the organiser''s official source and independent reporting, then approved at APPROVE V3 FINAL. Scores: initial NOYA judgement.' where id = 'f2042774-e656-4ff5-ad7f-2504386b9132' and calendar_status = 'VERIFIED';  -- wimbledon-2027
select set_config('noya.calendar_gate', 'off', true);

update public.intelligence set notes = 'Held at launch (3 Oct 2026): the date has already moved once (7 Apr -> 28 Nov 2026, regional situation) and only the promoter''s official ticketing confirms it. Not approved and not on the public calendar; re-check with the artist''s and promoter''s channels before approving.' where id = '1b37cea5-e949-4f4e-90ad-d62755f029b5' and calendar_status = 'VERIFIED';  -- shakira-pyramids-of-giza-2026

insert into public.approval_audit (action, result, actor, detail) values
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', '1218021c-645c-454f-97b7-47ead048da24', 'calendar_slug', 'el-gouna-film-festival-2026', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', '68158dc6-7c6f-4c69-8852-8fb8e4680747', 'calendar_slug', 'abu-simbel-sun-festival-october-2026', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', '94108f87-5858-4bce-88bc-e3e7f99e8096', 'calendar_slug', 'art-basel-paris-2026', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', 'cb97d931-8365-4ac2-9787-825cde715a57', 'calendar_slug', 'forever-is-now-06', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', 'daea469f-a0d4-4597-a17f-e0f5ae3af191', 'calendar_slug', 'cairo-international-film-festival-2026', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', '6715fc0f-9aab-444d-a903-dbae300ffc5a', 'calendar_slug', 'abu-dhabi-grand-prix-2026', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', '0fab885e-40f1-4051-8a95-daf7a9fcd46f', 'calendar_slug', 'art-basel-miami-beach-2026', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', 'd58e1b5a-b98b-4509-a150-16bf6519afa9', 'calendar_slug', 'french-alps-winter-season-2026-27', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', '83446988-2383-452c-b43c-fea22e07cf7f', 'calendar_slug', 'haute-couture-week-spring-summer-2027', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', '7b4b8a7c-9993-48f3-a04c-f0bd6c5ac298', 'calendar_slug', 'abu-simbel-sun-festival-february-2027', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', 'd38acc1a-ef0d-4ee7-aab5-a31dc3e63a9a', 'calendar_slug', 'paris-fashion-week-womenswear-fall-winter-2027', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', '7ce682ca-05ea-419f-98a9-9e2e6baafb27', 'calendar_slug', 'dubai-world-cup-2027', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', 'c3dfd10f-1101-4e8a-95e5-8cbc75a2fb48', 'calendar_slug', 'festival-de-cannes-2027', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', '8981a114-436e-41e8-a5c6-d77099aa5050', 'calendar_slug', 'monaco-grand-prix-2027', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', '046b1f38-d372-473d-a6d5-58f517c9bb85', 'calendar_slug', 'uefa-champions-league-final-2027', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', '6582907f-7b16-44f7-aeb1-3da95042764a', 'calendar_slug', 'royal-ascot-2027', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'OK', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', 'f2042774-e656-4ff5-ad7f-2504386b9132', 'calendar_slug', 'wimbledon-2027', 'rechecked', '2026-10-03')),
  ('CALENDAR_APPROVE', 'BLOCKED', 'Adam Elshazly (written approval, APPROVE V3 FINAL)', jsonb_build_object('intelligence_id', '1b37cea5-e949-4f4e-90ad-d62755f029b5', 'calendar_slug', 'shakira-pyramids-of-giza-2026', 'reason', 'date moved once (7 Apr -> 28 Nov 2026); held until re-confirmed'));

commit;
