-- Private Calendar research (4 Oct 2026), after the CEO's direction: "best events suitable for
-- NOYA and EGYPT". Events are added to the radar for Adam's approval; nothing here is approved
-- or published (approval stays with hq_calendar_approve, publishing with the Studio).
--
-- VERIFIED (9): dates checked on 4 Oct 2026 against the organiser's own site or official
-- ticketing. Five are in Egypt and fill the gap after 22 Feb 2027, when the launch calendar
-- has no Egypt event.
-- CANDIDATE (4), not proposed for approval yet:
--   - Art Basel Qatar and Frieze Abu Dhabi: Gulf conflict risk (EASA CZIB-2026-07 rated
--     UAE/Qatar airspace high-risk, extended to 30 Sep 2026; Art Dubai 2026 was postponed).
--   - Zamna Sharm El-Sheikh: off-brand for the public calendar, useful for lead generation.
--   - Cairo Design Week: dates only in the press so far.
-- Full research and sources: docs/briefs/2026-10-04_NOYA_EVENTS_AND_WEBSITE_QUALITY.md
set lock_timeout = '5s';

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Longines Global Champions Tour Cairo 2026: Giza, Cairo, 2026-10-22 to 2026-10-24', 'The Longines Global Champions Tour, the international show-jumping series, holds its first event in Egypt at the Pyramids of Giza from 22 to 24 October 2026, the first year of a five-year agreement.', 'CALENDAR_EVENT', 'SPORTS', 'EGYPT', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar research, 4 Oct 2026)', 'VERIFIED', 'EGYPT', 'Giza, Cairo', 'Pyramids of Giza', 'Egypt', 'Giza, Cairo', '2026-10-22', '2026-10-24', 'https://www.gcglobalchampions.com/news/lgct-2026', 'Longines Global Champions Tour', '2026-10-04', 85, 100, 70, 80, 'lgct-cairo-2026', 'calendarEvent.lgct-cairo-2026', 'lgct-cairo|2026-10', 'Dates checked on 4 Oct 2026 on the organiser''s site (2026 calendar: 22–24 October). Launched in Cairo with the Prime Minister; five-year agreement, so 2027 is likely (watch). Act now: 18 days away. Awaiting CEO approval. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Gala de Danza at the Grand Egyptian Museum: Giza, Cairo, 2026-11-05', 'Gala de Danza gives its first performance in the Middle East at the Grand Egyptian Museum on Thursday 5 November 2026, for the museum’s first anniversary: around 150 dancers, including principals of the Royal Ballet. Formal attire.', 'CALENDAR_EVENT', 'ENTERTAINMENT', 'EGYPT', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar research, 4 Oct 2026)', 'VERIFIED', 'EGYPT', 'Giza, Cairo', 'Grand Egyptian Museum', 'Egypt', 'Giza, Cairo', '2026-11-05', '2026-11-05', 'https://www.ticketsmarche.com/event/gala_de_danza_8840', 'Ticketsmarche (official ticketing, presented by GEM Experience)', '2026-10-04', 80, 100, 65, 70, 'gala-de-danza-grand-egyptian-museum-2026', 'calendarEvent.gala-de-danza-grand-egyptian-museum-2026', 'gala-de-danza-gem|2026-11', 'Dates checked on 4 Oct 2026 on the official ticketing page (5 November, 9 pm, Grand Egyptian Museum) and in Egyptian Streets / EnterpriseAM. Anchors a Cairo November week with Forever Is Now 06 and CIFF. Awaiting CEO approval. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('El Gouna IGFA Red Sea Championship 2027: El Gouna, Red Sea, 2027-02-04 to 2027-02-07', 'The International Game Fish Association’s big-game fishing championship on the Red Sea at El Gouna: captains’ meeting on Thursday 4 February 2027, two days of fishing, then the weigh-in and awards on Sunday 7 February. Teams of up to four anglers.', 'CALENDAR_EVENT', 'SPORTS', 'EGYPT', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar research, 4 Oct 2026)', 'VERIFIED', 'EGYPT', 'El Gouna, Red Sea', null, 'Egypt', 'El Gouna, Red Sea', '2027-02-04', '2027-02-07', 'https://igfa.org/igfa-red-sea-championship/', 'International Game Fish Association', '2026-10-04', 75, 100, 50, 80, 'el-gouna-igfa-red-sea-championship-2027', 'calendarEvent.el-gouna-igfa-red-sea-championship-2027', 'el-gouna-igfa-red-sea|2027-02', 'Dates checked on 4 Oct 2026 on igfa.org (programme 4–7 February 2027; team entry €4,000). NOYA angle: sportfishing yacht, team logistics, marina villa, flights. Awaiting CEO approval. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Total solar eclipse over Luxor: Luxor, 2027-08-02', 'A total solar eclipse crosses Upper Egypt on Monday 2 August 2027. Near Luxor, totality lasts up to about six minutes, the longest on land until 2114 (NASA gives a central duration of 6 minutes 23 seconds).', 'CALENDAR_EVENT', 'TRAVEL', 'EGYPT', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar research, 4 Oct 2026)', 'VERIFIED', 'EGYPT', 'Luxor', null, 'Egypt', 'Luxor', '2027-08-02', '2027-08-02', 'https://eclipse.gsfc.nasa.gov/SEgoogle/SEgoogle2001/SE2027Aug02Tgoogle.html', 'NASA Goddard Space Flight Center', '2026-10-04', 95, 100, 60, 100, 'total-solar-eclipse-luxor-2027', 'calendarEvent.total-solar-eclipse-luxor-2027', 'solar-eclipse-luxor|2027-08', 'Date and duration checked on 4 Oct 2026 against NASA''s eclipse page; also Forbes (16 Aug 2026) and the National Solar Observatory map. Egypt''s tourism ministry has a hosting committee (Ahram Online, reported). Lead time matters: Luxor hotels and Nile boats are expected to sell out early. August heat above 40°C. Awaiting CEO approval. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Sun Festival at Abu Simbel: Abu Simbel, Aswan, 2027-10-22', 'At sunrise the sun’s rays reach the inner sanctuary of the Great Temple of Ramses II and light the statues of Ramses II, Amun-Re and Re-Horakhty, leaving Ptah in shadow. Egypt’s Ministry of Tourism and Antiquities gives the dates as 22 October and 22 February each year.', 'CALENDAR_EVENT', 'ENTERTAINMENT', 'EGYPT', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar research, 4 Oct 2026)', 'VERIFIED', 'EGYPT', 'Abu Simbel, Aswan', 'Great Temple of Ramses II', 'Egypt', 'Abu Simbel, Aswan', '2027-10-22', '2027-10-22', 'https://egymonuments.gov.eg/en/archaeological-sites/abu-simbel', 'Ministry of Tourism and Antiquities', '2026-10-04', 70, 100, 40, 85, 'abu-simbel-sun-festival-october-2027', 'calendarEvent.abu-simbel-sun-festival-october-2027', 'abu-simbel-sun-festival|2027-10', 'Next occurrence of the recurring date (22 October each year, per the Ministry). Awaiting CEO approval. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Snow Polo World Cup St. Moritz 2027: St. Moritz, 2027-01-22 to 2027-01-24', 'The 42nd Snow Polo World Cup: high-goal polo on the frozen lake at St. Moritz, from Friday 22 to Sunday 24 January 2027.', 'CALENDAR_EVENT', 'SPORTS', 'EUROPE', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar research, 4 Oct 2026)', 'VERIFIED', 'SPORT', 'St. Moritz', 'Lake St. Moritz', 'Switzerland', 'St. Moritz', '2027-01-22', '2027-01-24', 'https://www.snowpolo-stmoritz.com/tournament-2027/42nd-snow-polo-world-cup-st-moritz-2027/', 'Snow Polo World Cup St. Moritz', '2026-10-04', 75, 10, 70, 80, 'snow-polo-world-cup-st-moritz-2027', 'calendarEvent.snow-polo-world-cup-st-moritz-2027', 'snow-polo-st-moritz|2027-01', 'Dates checked on 4 Oct 2026 on the organiser''s site. Pairs with White Turf (7, 14 and 21 February 2027). Awaiting CEO approval. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Goodwood Festival of Speed 2027: Chichester, West Sussex, 2027-07-15 to 2027-07-18', 'Four days of cars and motorsport in the grounds of Goodwood House, from 15 to 18 July 2027.', 'CALENDAR_EVENT', 'SPORTS', 'UK', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar research, 4 Oct 2026)', 'VERIFIED', 'MOTORSPORT', 'Chichester, West Sussex', 'Goodwood House', 'United Kingdom', 'Chichester, West Sussex', '2027-07-15', '2027-07-18', 'https://www.goodwood.com/grr/event-coverage/festival-of-speed/2027-fos-dates-revealed/', 'Goodwood', '2026-10-04', 75, 10, 70, 75, 'goodwood-festival-of-speed-2027', 'calendarEvent.goodwood-festival-of-speed-2027', 'goodwood-festival-of-speed|2027-07', 'Dates checked on 4 Oct 2026 on goodwood.com (general sale opens November 2026). A fixture of Gulf families'' English summer. Awaiting CEO approval. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Ryder Cup 2027: Adare, County Limerick, 2027-09-17 to 2027-09-19', 'Europe against the United States at Adare Manor in the Ryder Cup’s centenary year: practice days from Monday 13 September, then three days of matches from Friday 17 to Sunday 19 September 2027.', 'CALENDAR_EVENT', 'SPORTS', 'EUROPE', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar research, 4 Oct 2026)', 'VERIFIED', 'SPORT', 'Adare, County Limerick', 'Adare Manor', 'Ireland', 'Adare, County Limerick', '2027-09-17', '2027-09-19', 'https://www.rydercup.com/news-media/dates-announced-for-the-2027-ryder-cup', 'Ryder Cup', '2026-10-04', 85, 10, 75, 90, 'ryder-cup-2027', 'calendarEvent.ryder-cup-2027', 'ryder-cup|2027-09', 'Dates checked on 4 Oct 2026 on rydercup.com (week 13–19 September; matches 17–19). Very few rooms near Adare: estates, castles, jets to Shannon, helicopters. Awaiting CEO approval. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Monaco Yacht Show 2027: Monaco, 2027-09-22 to 2027-09-25', 'The superyacht industry’s principal show, at Port Hercule from 22 to 25 September 2027. The first day is by invitation; general access runs from Thursday 23 September.', 'CALENDAR_EVENT', 'EVENTS', 'EUROPE', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar research, 4 Oct 2026)', 'VERIFIED', 'ENTERTAINMENT', 'Monaco', 'Port Hercule', 'Monaco', 'Monaco', '2027-09-22', '2027-09-25', 'https://www.monacoyachtshow.com/en/faq', 'Monaco Yacht Show', '2026-10-04', 75, 10, 65, 80, 'monaco-yacht-show-2027', 'calendarEvent.monaco-yacht-show-2027', 'monaco-yacht-show|2027-09', 'Dates checked on 4 Oct 2026 (organiser FAQ; yacht-broker listings agree). Fits NOYA''s yacht charter work. The site has no yachting category, so it sits under Entertainment. Awaiting CEO approval. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

-- Candidates: on the radar, not proposed for approval yet.
insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Art Basel Qatar 2027: Doha, 2027-01-28 to 2027-01-30', 'Art Basel’s fair in Doha: public days from 28 to 30 January 2027, after preview days on 26 and 27 January.', 'CALENDAR_EVENT', 'EVENTS', 'MIDDLE_EAST', 'WATCH', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar research, 4 Oct 2026)', 'CANDIDATE', 'FASHION_CULTURE', 'Doha', null, 'Qatar', 'Doha', '2027-01-28', '2027-01-30', 'https://www.artbasel.com/qatar', 'Art Basel', '2026-10-04', 70, 20, 70, 70, 'art-basel-qatar-2027', 'calendarEvent.art-basel-qatar-2027', 'art-basel-qatar|2027-01', 'HOLD (Gulf conflict risk): EASA CZIB-2026-07 rated Qatar/UAE airspace high-risk, extended to 30 Sep 2026; Art Dubai 2026 was postponed. Dates from the organiser via the research agent, not re-checked by hand. Re-check monthly before proposing.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Frieze Abu Dhabi 2026: Abu Dhabi, 2026-11-19 to 2026-11-22', 'Frieze’s art fair in Abu Dhabi from 19 to 22 November 2026, with an invitation-only first day.', 'CALENDAR_EVENT', 'EVENTS', 'MIDDLE_EAST', 'WATCH', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar research, 4 Oct 2026)', 'CANDIDATE', 'FASHION_CULTURE', 'Abu Dhabi', null, 'United Arab Emirates', 'Abu Dhabi', '2026-11-19', '2026-11-22', 'https://www.frieze.com/article/gallery-applications-open-frieze-abu-dhabi-2026', 'Frieze', '2026-10-04', 65, 20, 65, 65, 'frieze-abu-dhabi-2026', 'calendarEvent.frieze-abu-dhabi-2026', 'frieze-abu-dhabi|2026-11', 'HOLD (Gulf conflict risk, as Art Basel Qatar). Reported as Frieze''s first Abu Dhabi edition; dates via the research agent, not re-checked by hand.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Zamna Sharm El-Sheikh 2026: Sharm El-Sheikh, 2026-11-20 to 2026-11-22', 'Zamna’s electronic-music festival at Khoroum Valley, Sharm El-Sheikh, from 20 to 22 November 2026.', 'CALENDAR_EVENT', 'ENTERTAINMENT', 'EGYPT', 'WATCH', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar research, 4 Oct 2026)', 'CANDIDATE', 'EGYPT', 'Sharm El-Sheikh', 'Khoroum Valley', 'Egypt', 'Sharm El-Sheikh', '2026-11-20', '2026-11-22', 'https://zamnafestival.com/news/zamna-sharm-el-sheikh-2026-pre-registration-is-now-open', 'Zamna Festival', '2026-10-04', 45, 90, 40, 60, 'zamna-sharm-el-sheikh-2026', 'calendarEvent.zamna-sharm-el-sheikh-2026', 'zamna-sharm|2026-11', 'Not recommended for the public calendar (brand fit: a mass festival). Useful for lead generation: villa, yacht and transfer demand in Sharm that weekend.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Cairo Design Week 2026: Cairo, 2026-11-19 to 2026-11-28', 'Cairo Design Week, the city-wide design festival; the press reports 19 to 28 November 2026.', 'CALENDAR_EVENT', 'EVENTS', 'EGYPT', 'WATCH', 'NEW', 'INFERRED', 'Claude (Private Calendar research, 4 Oct 2026)', 'CANDIDATE', 'EGYPT', 'Cairo', null, 'Egypt', 'Cairo', '2026-11-19', '2026-11-28', null, 'Press (Arab News, Dezeen)', null, 60, 100, 50, 55, 'cairo-design-week-2026', 'calendarEvent.cairo-design-week-2026', 'cairo-design-week|2026-11', 'WATCH: dates only in the press; cairodesignweek.net still shows 2025. Re-check weekly; propose once the official site confirms.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

-- NOT YET APPLIED (4 Oct 2026): the Supabase connector held these two updates for a confirmation
-- it cannot show. The inserts above are applied. Paste this section into the SQL editor once.
-- Playbooks, as for the launch set: the travel playbook for events clients travel to; the Egypt
-- sports playbook stays on LGCT Cairo and the IGFA (sporting events in Egypt); Gala de Danza,
-- Zamna and Cairo Design Week keep the festival playbook the enrich trigger gave them.
update public.intelligence set
  playbook_code = 'EVENT_TRAVEL', product_codes = '{}', decision_roles = '{}', services = '{}',
  commercial_angle = null, problem_noya_solves = null,
  next_action = 'Read the dates on the official page and approve for the Private Calendar; then shortlist the clients and EAs to offer it to.'
where calendar_slug in ('total-solar-eclipse-luxor-2027', 'abu-simbel-sun-festival-october-2027', 'snow-polo-world-cup-st-moritz-2027',
  'goodwood-festival-of-speed-2027', 'ryder-cup-2027', 'monaco-yacht-show-2027', 'art-basel-qatar-2027', 'frieze-abu-dhabi-2026')
  and captured_by = 'Claude (Private Calendar research, 4 Oct 2026)';

update public.intelligence set playbook_code = 'SPORTS_EVENT_EGYPT'
where calendar_slug = 'lgct-cairo-2026' and playbook_code is null and captured_by = 'Claude (Private Calendar research, 4 Oct 2026)';
