-- Deterministic fact set for workflow 11 "NOYA — DAILY COMMERCIAL ACTION BRIEF".
-- Read-only: it consolidates and ranks what departments 02-09, 05, 13 and the CRM
-- already produced. No research, no writes. Every Adam action it returns is an
-- existing task (task_id), so the brief never invents work the task list lacks.
-- Value labels: opportunity values are workflow MODEL_ESTIMATEs (no scope or
-- proposal exists in the schema); ACTUAL comes only from the revenue table.

create or replace function public.daily_action_brief_facts()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
with
open_tasks as (
  select t.*, o.company_name as opp_company, o.opportunity_type, o.status as opp_status,
         o.estimated_value, o.currency, o.destination, o.priority as opp_priority,
         coalesce(co.source, o.run_id) as dept_source,
         c.first_name, c.last_name, c.position, c.email_status, c.linkedin,
         (select e.status from outbound_emails e where e.opportunity_id = t.opportunity_id
            order by e.created_at desc limit 1) as outbound_status
  from tasks t
  left join opportunities o on o.id = t.opportunity_id
  left join companies co on co.id = coalesce(t.company_id, o.company_id)
  left join contacts c on c.id = coalesce(t.contact_id, o.contact_id)
  where t.status in ('OPEN', 'IN_PROGRESS')
),
ranked as (
  select ot.*,
    case
      when ot.created_by ilike '10d%' or ot.task_type in ('WEBSITE_ENQUIRY', 'INBOUND_ENQUIRY') then 1
      when ot.task_type in ('MEETING_ACTION') or (ot.task_type = 'REPLY_ACTION' and ot.created_by ilike '13%') then 2
      when ot.task_type = 'REPLY_ACTION' then 3
      when ot.task_type = 'OUTREACH_DRAFT_READY' then 4
      when ot.task_type = 'SALES_OUTREACH_APPROVAL'
           and coalesce(ot.position, '') ~* '(founder|chief executive|\mceo\M|president|chairman|owner|managing partner)'
           and coalesce(ot.position, '') !~* 'vice president' then 5
      when ot.task_type = 'SALES_OUTREACH_APPROVAL' then 6
      when ot.task_type = 'OUTREACH_FOLLOW_UP' and ot.due_at <= now() + interval '1 day' then 7
      else 8
    end as rank_bucket
  from open_tasks ot
),
active_opps as (
  select o.id, o.company_name, o.opportunity_type, o.status, o.priority, o.estimated_value, o.currency,
    o.destination, left(coalesce(o.reason, ''), 280) as reason,
    left(coalesce(o.suggested_approach, ''), 180) as suggested_approach, o.next_action,
    coalesce(co.source, o.run_id) as dept_source, coalesce(co.company_type, o.company_type) as company_type,
    coalesce(co.sector, o.sector) as sector,
    c.first_name || ' ' || coalesce(c.last_name, '') as contact_name, c.position as contact_role, c.email_status,
    (select string_agg(t.title, ' | ') from tasks t where t.opportunity_id = o.id and t.status in ('OPEN', 'IN_PROGRESS', 'WAITING')) as open_tasks,
    case
      when coalesce(co.source, '') ilike '%Wedding%' or coalesce(co.company_type, o.company_type, '') ~* '(wedding|event plann|event design)' then 'WEDDING_EVENT'
      when coalesce(co.source, '') ilike '%Brand & Production%' then 'BRAND_TRIP_SHOOT'
      when coalesce(o.opportunity_type, '') ~ '(TALENT_TRAVEL|PRIVATE_TRAVEL)' or coalesce(co.company_type, o.company_type, '') ~* '(_creator|public_figure)' then 'TALENT_PRIVATE'
      when coalesce(co.company_type, o.company_type, '') ~* '(hotel|resort|hospitality)' then 'HOTEL_CONTENT'
      when coalesce(co.company_type, o.company_type, '') ~* '(bank|wealth|investment|family office|corporate)' then 'CORPORATE_RECURRING'
      when coalesce(co.company_type, o.company_type, '') ~* '(concierge|aviation|travel|expedition|dmc|pr_agency)' then 'PARTNER_CHANNEL'
      when coalesce(co.source, o.run_id, '') ilike '%Brand%'
           or coalesce(co.company_type, o.company_type, '') ~* '(brand|fashion|cosmetic|beauty|jewel|watch|automotive|airline|sportswear|marketing agency|creative agency)'
           or coalesce(o.opportunity_type, '') ~* '(creator|campaign|production|shoot|influencer|brand trip)' then 'BRAND_TRIP_SHOOT'
      else 'OTHER'
    end as category
  from opportunities o
  left join companies co on co.id = o.company_id
  left join contacts c on c.id = o.contact_id
  where o.status not in ('WON', 'LOST', 'ARCHIVED')
)
select jsonb_build_object(
  'generated_at', now(),
  'brief_date_cairo', to_char(now() at time zone 'Africa/Cairo', 'FMDay FMDD FMMonth YYYY'),
  'value_policy', 'Opportunity values are MODEL_ESTIMATE (generated by discovery workflows; no scope or proposal behind them). Never present them as pipeline or revenue. ACTUAL = revenue table only. PROPOSED = none recorded.',
  'actual_revenue', (select coalesce(jsonb_agg(jsonb_build_object('currency', currency, 'amount', amt)), '[]'::jsonb)
                     from (select currency, sum(amount) amt from revenue group by currency) r),
  'adam_actions', (
    select coalesce(jsonb_agg(x order by (x->>'rank_bucket')::int, (x->>'task_priority')::int desc, (x->>'due_at')), '[]'::jsonb) from (
      select jsonb_build_object(
        'task_id', r.id, 'task_type', r.task_type, 'title', r.title, 'rank_bucket', r.rank_bucket,
        'p_level', case when r.rank_bucket <= 4 or r.due_at < now() + interval '1 day' then 'P1'
                        when r.rank_bucket <= 6 or r.due_at < now() + interval '2 days' then 'P2' else 'P3' end,
        'task_priority', r.priority, 'due_at', r.due_at, 'company', coalesce(r.opp_company, ''),
        'department', coalesce(r.dept_source, r.created_by),
        'contact', nullif(btrim(coalesce(r.first_name, '') || ' ' || coalesce(r.last_name, '')), ''),
        'contact_role', r.position, 'email_status', r.email_status, 'linkedin', r.linkedin,
        'opportunity_type', r.opportunity_type, 'opportunity_status', r.opp_status, 'destination', r.destination,
        'value', r.estimated_value, 'currency', r.currency,
        'value_label', case when r.estimated_value is null then 'UNKNOWN' else 'MODEL_ESTIMATE' end,
        'outbound_status', r.outbound_status,
        'task_head', left(coalesce(r.description, ''), 260),
        'task_latest', right(coalesce(r.description, ''), 650)
      ) x
      from ranked r
    ) s
  ),
  'replies_14d', (
    select coalesce(jsonb_agg(jsonb_build_object(
      'received_at', l.received_at, 'classification', l.classification, 'match', l.match_method,
      'from', l.detail->>'from', 'subject', l.detail->>'subject', 'summary', l.detail->>'summary',
      'company', o.company_name, 'task_id', l.task_id,
      'is_human_actionable', coalesce(l.classification, '') in ('POSITIVE', 'NEEDS_INFO', 'MEETING_REQUEST', 'NOT_NOW', 'REFERRAL', 'DECLINED', 'UNKNOWN')
    ) order by l.received_at desc), '[]'::jsonb)
    from gmail_sync_ledger l left join opportunities o on o.id = l.opportunity_id
    where l.kind = 'INBOUND_REPLY' and l.received_at > now() - interval '14 days'
  ),
  'ready_to_send', (
    select coalesce(jsonb_agg(jsonb_build_object('company', o.company_name, 'to', e.to_email, 'subject', e.subject,
      'drafted_at', e.completed_at, 'gmail_draft_id', e.gmail_draft_id)), '[]'::jsonb)
    from outbound_emails e join opportunities o on o.id = e.opportunity_id where e.status = 'DRAFTED'
  ),
  'adam_review_required', (
    select coalesce(jsonb_agg(jsonb_build_object('company', o.company_name, 'contact', c.first_name || ' ' || coalesce(c.last_name, ''),
      'role', c.position, 'email_status', c.email_status, 'subject', d->>'subject', 'body', d->>'body',
      'draft_version', d->>'version', 'follow_up_plan', left(coalesce(d->>'follow_up_plan', ''), 300),
      'value', o.estimated_value, 'value_label', 'MODEL_ESTIMATE')), '[]'::jsonb)
    from opportunities o join contacts c on c.id = o.contact_id
    cross join lateral (select hq_current_draft(o.id) d) x
    where c.email_status = 'VERIFIED' and d is not null
      and not exists (select 1 from outbound_emails e where e.opportunity_id = o.id and e.status in ('APPROVED', 'PROCESSING', 'DRAFTED', 'SENT'))
      and not exists (select 1 from approval_queue_state q where q.opportunity_id = o.id)
      and o.status not in ('WON', 'LOST', 'ARCHIVED', 'CONTACTED')
  ),
  'active_opportunities', (
    select coalesce(jsonb_agg(to_jsonb(a) || jsonb_build_object('value_label',
      case when a.estimated_value is null then 'UNKNOWN' else 'MODEL_ESTIMATE' end) order by a.priority desc nulls last), '[]'::jsonb)
    from active_opps a
  ),
  'follow_ups_due', (
    select coalesce(jsonb_agg(jsonb_build_object('task_id', t.id, 'title', t.title, 'due_at', t.due_at, 'company', o.company_name)), '[]'::jsonb)
    from tasks t left join opportunities o on o.id = t.opportunity_id
    where t.task_type = 'OUTREACH_FOLLOW_UP' and t.status in ('OPEN', 'IN_PROGRESS') and t.due_at <= now() + interval '2 days'
  ),
  'waiting_for_contact', (
    select coalesce(jsonb_agg(jsonb_build_object('task_id', t.id, 'title', t.title, 'company', o.company_name,
      'value', o.estimated_value, 'value_label', 'MODEL_ESTIMATE', 'note', right(coalesce(t.description, ''), 260))), '[]'::jsonb)
    from tasks t left join opportunities o on o.id = t.opportunity_id where t.status = 'WAITING'
  ),
  'task_hygiene', jsonb_build_object(
    'open', (select count(*) from tasks where status in ('OPEN', 'IN_PROGRESS')),
    'waiting', (select count(*) from tasks where status = 'WAITING'),
    'overdue', (select count(*) from tasks where status in ('OPEN', 'IN_PROGRESS') and due_at < now()),
    'duplicate_groups', (select count(*) from (select opportunity_id, task_type from tasks
        where status in ('OPEN', 'IN_PROGRESS', 'WAITING') and opportunity_id is not null group by 1, 2 having count(*) > 1) d),
    'orphans', (select count(*) from tasks where status in ('OPEN', 'IN_PROGRESS') and opportunity_id is null and company_id is null),
    'open_on_closed_opps', (select count(*) from tasks t join opportunities o on o.id = t.opportunity_id
        where t.status in ('OPEN', 'IN_PROGRESS') and o.status in ('WON', 'LOST', 'ARCHIVED')),
    'qualified_without_next_action', (select coalesce(jsonb_agg(o.company_name), '[]'::jsonb) from opportunities o
        where o.status in ('NEW', 'READY', 'CONTACTED') and o.priority >= 70
          and not exists (select 1 from tasks t where t.opportunity_id = o.id and t.status in ('OPEN', 'IN_PROGRESS', 'WAITING')))
  ),
  'discovery_last_24h', (
    select coalesce(jsonb_agg(jsonb_build_object('department', d.src, 'qualified_opportunities', d.opps, 'watchlist_companies', d.watch)), '[]'::jsonb)
    from (
      select src, sum(opps) opps, sum(watch) watch from (
        select coalesce(co.source, 'UNKNOWN') src, 1 opps, 0 watch
          from opportunities o left join companies co on co.id = o.company_id where o.created_at > now() - interval '24 hours'
        union all
        select coalesce(source, 'UNKNOWN'), 0, 1 from companies where created_at > now() - interval '24 hours' and source ilike '%WATCHLIST%'
      ) u group by src
    ) d
  )
);
$$;

revoke all on function public.daily_action_brief_facts() from public, anon, authenticated;
grant execute on function public.daily_action_brief_facts() to service_role;
