-- Private Calendar launch set on the radar (3 Oct 2026): the 18 events on the V3 website,
-- each with its official source, as VERIFIED candidates. Approval stays with Adam
-- (hq_calendar_approve); the two events already on the radar get the calendar fields.
set lock_timeout = '5s';

-- El Gouna Film Festival 2026: already on the radar; add the calendar fields
update public.intelligence set calendar_status = 'VERIFIED', calendar_category = 'EGYPT', city = 'El Gouna, Red Sea', venue = null, country = 'Egypt', destination = 'El Gouna, Red Sea', event_date = '2026-10-15', event_end = '2026-10-23', source_url = 'https://elgounafilmfestival.com/accreditation/', source_name = 'El Gouna Film Festival', source_checked_at = '2026-10-03', relevance_score = 80, egypt_relevance = 95, access_potential = 70, travel_opportunity = 80, calendar_slug = 'el-gouna-film-festival-2026', sanity_document_id = 'calendarEvent.el-gouna-film-festival-2026', dedupe_key = 'el-gouna-film-festival|2026-10', notes = 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.' where id = '1218021c-645c-454f-97b7-47ead048da24' and calendar_slug is null;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Sun Festival at Abu Simbel: Abu Simbel, Aswan, 2026-10-22', 'At sunrise the sun’s rays reach the inner sanctuary of the Great Temple of Ramses II and light the statues of Ramses II, Amun-Re and Re-Horakhty, leaving Ptah in shadow. Egypt’s Ministry of Tourism and Antiquities gives the dates as 22 October and 22 February each year.', 'CALENDAR_EVENT', 'ENTERTAINMENT', 'EGYPT', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'EGYPT', 'Abu Simbel, Aswan', 'Great Temple of Ramses II', 'Egypt', 'Abu Simbel, Aswan', '2026-10-22', '2026-10-22', 'https://egymonuments.gov.eg/en/events/the-unique-biannual-solar-alignment-phenomenon-at-the-temple-of-ramses-ii-in-abu-simbel', 'Ministry of Tourism and Antiquities', '2026-10-03', 75, 100, 40, 85, 'abu-simbel-sun-festival-october-2026', 'calendarEvent.abu-simbel-sun-festival-october-2026', 'abu-simbel-sun-festival|2026-10', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Art Basel Paris 2026: Paris, 2026-10-23 to 2026-10-25', 'Art Basel’s Paris fair at the Grand Palais, with galleries across its Galeries, Emergence and Premise sectors. Public days run from 23 to 25 October, after invitation-only Preview Days on 21 and 22 October.', 'CALENDAR_EVENT', 'EVENTS', 'EUROPE', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'FASHION_CULTURE', 'Paris', 'Grand Palais', 'France', 'Paris', '2026-10-23', '2026-10-25', 'https://www.artbasel.com/paris', 'Art Basel', '2026-10-03', 85, 10, 80, 85, 'art-basel-paris-2026', 'calendarEvent.art-basel-paris-2026', 'art-basel-paris|2026-10', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Forever Is Now 06: Giza, Cairo, 2026-11-04 to 2026-11-28', 'The sixth edition of Art D’Égypte’s open-air contemporary art exhibition on the Giza plateau, set among the pyramids. The 2026 edition is led primarily by women artists.', 'CALENDAR_EVENT', 'ENTERTAINMENT', 'EGYPT', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'EGYPT', 'Giza, Cairo', 'Pyramids of Giza', 'Egypt', 'Giza, Cairo', '2026-11-04', '2026-11-28', 'https://artdegypte.org/event/forever-is-now-06/', 'Art D’Égypte', '2026-10-03', 80, 100, 60, 80, 'forever-is-now-06', 'calendarEvent.forever-is-now-06', 'forever-is-now-06|2026-11', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Cairo International Film Festival 2026: Cairo, 2026-11-11 to 2026-11-20', 'The 47th edition of Cairo’s international film festival, a FIAPF-accredited competitive festival held under the auspices of Egypt’s Ministry of Culture.', 'CALENDAR_EVENT', 'ENTERTAINMENT', 'EGYPT', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'EGYPT', 'Cairo', null, 'Egypt', 'Cairo', '2026-11-11', '2026-11-20', 'https://ciff.org.eg/en/media/news/ciff-announces-the-opening-of-submissions-for-its-47th-edition', 'Cairo International Film Festival', '2026-10-03', 65, 95, 60, 65, 'cairo-international-film-festival-2026', 'calendarEvent.cairo-international-film-festival-2026', 'cairo-international-film-festival|2026-11', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

-- Shakira at the Pyramids of Giza: already on the radar; add the calendar fields
update public.intelligence set calendar_status = 'VERIFIED', calendar_category = 'EGYPT', city = 'Giza, Cairo', venue = 'Pyramids of Giza', country = 'Egypt', destination = 'Giza, Cairo', event_date = '2026-11-28', event_end = '2026-11-28', source_url = 'https://ticketegypt.venflare.com/events/6f9c1782-c4d5-4f9a-b2b1-29372e2bdda9', source_name = 'Ticket Egypt (official ticketing for Venture Lifestyle)', source_checked_at = '2026-10-03', relevance_score = 85, egypt_relevance = 100, access_potential = 85, travel_opportunity = 85, calendar_slug = 'shakira-pyramids-of-giza-2026', sanity_document_id = 'calendarEvent.shakira-pyramids-of-giza-2026', dedupe_key = 'shakira-pyramids-of-giza|2026-11', notes = 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.' where id = '1b37cea5-e949-4f4e-90ad-d62755f029b5' and calendar_slug is null;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Abu Dhabi Grand Prix 2026: Abu Dhabi, 2026-12-04 to 2026-12-06', 'The scheduled final round of the 2026 Formula 1 World Championship at Yas Marina Circuit on Yas Island: practice on Friday 4 December, qualifying on Saturday and the race on Sunday 6 December.', 'CALENDAR_EVENT', 'SPORTS', 'MIDDLE_EAST', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'MOTORSPORT', 'Abu Dhabi', 'Yas Marina Circuit', 'United Arab Emirates', 'Abu Dhabi', '2026-12-04', '2026-12-06', 'https://www.formula1.com/en/racing/2026/united-arab-emirates', 'Formula 1', '2026-10-03', 85, 40, 90, 85, 'abu-dhabi-grand-prix-2026', 'calendarEvent.abu-dhabi-grand-prix-2026', 'abu-dhabi-grand-prix|2026-12', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Art Basel Miami Beach 2026: Miami Beach, 2026-12-04 to 2026-12-06', 'Art Basel’s Miami Beach fair at the Miami Beach Convention Center: invitation-only preview days on 2 and 3 December, followed by public days from 4 to 6 December.', 'CALENDAR_EVENT', 'EVENTS', 'GLOBAL', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'FASHION_CULTURE', 'Miami Beach', 'Miami Beach Convention Center', 'United States', 'Miami Beach', '2026-12-04', '2026-12-06', 'https://www.artbasel.com/miami-beach/at-the-show', 'Art Basel', '2026-10-03', 70, 5, 75, 80, 'art-basel-miami-beach-2026', 'calendarEvent.art-basel-miami-beach-2026', 'art-basel-miami-beach|2026-12', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Winter season in the French Alps: Courchevel and Méribel, 2026-12-04 to 2027-04-18', 'The 2026/27 ski season in Courchevel and Méribel, neighbouring resorts in Les 3 Vallées. Courchevel’s lifts open on 4 December 2026 and Méribel’s on 5 December; both close on 18 April 2027.', 'CALENDAR_EVENT', 'TRAVEL', 'EUROPE', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'SEASONAL', 'Courchevel and Méribel', 'Les 3 Vallées', 'France', 'Courchevel and Méribel', '2026-12-04', '2027-04-18', 'https://courchevel.com/en/quand-partir-au-ski/', 'Courchevel Tourisme', '2026-10-03', 80, 10, 30, 95, 'french-alps-winter-season-2026-27', 'calendarEvent.french-alps-winter-season-2026-27', 'french-alps-winter-season|2026-12', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Haute Couture Week, Spring/Summer 2027: Paris, 2027-01-25 to 2027-01-28', 'The official Haute Couture calendar for the Spring/Summer 2027 collections, organised in Paris by the Fédération de la Haute Couture et de la Mode, which publishes the detailed show schedule closer to the season.', 'CALENDAR_EVENT', 'EVENTS', 'EUROPE', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'FASHION_CULTURE', 'Paris', null, 'France', 'Paris', '2027-01-25', '2027-01-28', 'https://www.fhcm.paris/en/upcoming-seasons-and-previous-editions', 'Fédération de la Haute Couture et de la Mode', '2026-10-03', 75, 10, 85, 80, 'haute-couture-week-spring-summer-2027', 'calendarEvent.haute-couture-week-spring-summer-2027', 'haute-couture-week-spring-summer|2027-01', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Sun Festival at Abu Simbel: Abu Simbel, Aswan, 2027-02-22', 'At sunrise the sun’s rays reach the inner sanctuary of the Great Temple of Ramses II and light the statues of Ramses II, Amun-Re and Re-Horakhty, leaving Ptah in shadow. Egypt’s Ministry of Tourism and Antiquities gives the dates as 22 February and 22 October each year.', 'CALENDAR_EVENT', 'ENTERTAINMENT', 'EGYPT', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'EGYPT', 'Abu Simbel, Aswan', 'Great Temple of Ramses II', 'Egypt', 'Abu Simbel, Aswan', '2027-02-22', '2027-02-22', 'https://egymonuments.gov.eg/en/archaeological-sites/abu-simbel', 'Ministry of Tourism and Antiquities', '2026-10-03', 70, 100, 40, 85, 'abu-simbel-sun-festival-february-2027', 'calendarEvent.abu-simbel-sun-festival-february-2027', 'abu-simbel-sun-festival|2027-02', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Paris Fashion Week Womenswear, Fall/Winter 2027: Paris, 2027-03-01 to 2027-03-09', 'The official Paris womenswear ready-to-wear calendar for the Fall/Winter 2027–2028 collections, organised by the Fédération de la Haute Couture et de la Mode, which publishes the detailed schedule closer to the season.', 'CALENDAR_EVENT', 'EVENTS', 'EUROPE', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'FASHION_CULTURE', 'Paris', null, 'France', 'Paris', '2027-03-01', '2027-03-09', 'https://www.fhcm.paris/en/upcoming-seasons-and-previous-editions', 'Fédération de la Haute Couture et de la Mode', '2026-10-03', 75, 10, 85, 80, 'paris-fashion-week-womenswear-fall-winter-2027', 'calendarEvent.paris-fashion-week-womenswear-fall-winter-2027', 'paris-fashion-week-womenswear-fall-winter|2027-03', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Dubai World Cup 2027: Dubai, 2027-03-27', 'The Dubai World Cup meeting at Meydan Racecourse closes the 2026–2027 UAE racing season, with a nine-race card headed by the US$12 million Group 1 Dubai World Cup.', 'CALENDAR_EVENT', 'SPORTS', 'MIDDLE_EAST', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'SPORT', 'Dubai', 'Meydan Racecourse', 'United Arab Emirates', 'Dubai', '2027-03-27', '2027-03-27', 'https://emiratesracing.com/news/the-emirates-racing-authority-era-has-announced-the-official-schedule-for-the-2026-2027-uae-horse-racing-season', 'Emirates Racing Authority', '2026-10-03', 75, 40, 85, 80, 'dubai-world-cup-2027', 'calendarEvent.dubai-world-cup-2027', 'dubai-world-cup|2027-03', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Festival de Cannes 2027: Cannes, 2027-05-11 to 2027-05-22', 'The 80th edition of the Festival de Cannes, the international film festival held each May on the Croisette. The festival has given the dates as 11 to 22 May 2027.', 'CALENDAR_EVENT', 'ENTERTAINMENT', 'EUROPE', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'ENTERTAINMENT', 'Cannes', 'Palais des Festivals et des Congrès', 'France', 'Cannes', '2027-05-11', '2027-05-22', 'https://www.festival-cannes.com/en/press/press-releases/thierry-fremaux-reflects-on-the-79th-edition-in-an-interview-with-variety/', 'Festival de Cannes', '2026-10-03', 80, 15, 85, 90, 'festival-de-cannes-2027', 'calendarEvent.festival-de-cannes-2027', 'festival-de-cannes|2027-05', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Monaco Grand Prix 2027: Monaco, 2027-06-04 to 2027-06-06', 'The 84th Grand Prix de Monaco, run for the first time in 2027 as a Sprint weekend: Sprint Qualifying on Friday, the Sprint and Grand Prix qualifying on Saturday, and the Grand Prix on Sunday 6 June.', 'CALENDAR_EVENT', 'SPORTS', 'EUROPE', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'MOTORSPORT', 'Monaco', 'Circuit de Monaco', 'Monaco', 'Monaco', '2027-06-04', '2027-06-06', 'https://www.formula1.com/en/latest/article/formula-1-reveals-calendar-for-2027-season-with-10-sprint-events.5J8ePLyjRuMyWEIDNUKgY4', 'Formula 1', '2026-10-03', 95, 15, 95, 95, 'monaco-grand-prix-2027', 'calendarEvent.monaco-grand-prix-2027', 'monaco-grand-prix|2027-06', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('UEFA Champions League Final 2027: Madrid, 2027-06-05', 'The final of the 2026/27 UEFA Champions League at the Estadio Metropolitano in Madrid on Saturday 5 June 2027, the stadium’s second Champions League final after 2019.', 'CALENDAR_EVENT', 'SPORTS', 'EUROPE', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'SPORT', 'Madrid', 'Estadio Metropolitano', 'Spain', 'Madrid', '2027-06-05', '2027-06-05', 'https://www.uefa.com/uefachampionsleague/news/02a6-20d57cfcd03e-407c22a7f465-1000--2026-27-champions-league-teams-dates-draws-format-final/', 'UEFA', '2026-10-03', 85, 30, 90, 85, 'uefa-champions-league-final-2027', 'calendarEvent.uefa-champions-league-final-2027', 'uefa-champions-league-final|2027-06', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Royal Ascot 2027: Ascot, Berkshire, 2027-06-15 to 2027-06-19', 'The five-day Royal Ascot meeting at Ascot Racecourse in Berkshire, from Tuesday 15 to Saturday 19 June 2027, with dress codes set by the racecourse for each enclosure.', 'CALENDAR_EVENT', 'SPORTS', 'UK', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'SPORT', 'Ascot, Berkshire', 'Ascot Racecourse', 'United Kingdom', 'Ascot, Berkshire', '2027-06-15', '2027-06-19', 'https://www.ascot.com/royal-ascot', 'Ascot Racecourse', '2026-10-03', 75, 10, 85, 80, 'royal-ascot-2027', 'calendarEvent.royal-ascot-2027', 'royal-ascot|2027-06', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;

insert into public.intelligence (title, summary, intelligence_type, category, region, stage, status, provenance, captured_by, calendar_status, calendar_category, city, venue, country, destination, event_date, event_end, source_url, source_name, source_checked_at, relevance_score, egypt_relevance, access_potential, travel_opportunity, calendar_slug, sanity_document_id, dedupe_key, notes)
values ('Wimbledon 2027: London, 2027-06-28 to 2027-07-11', 'The Championships, the grass-court Grand Slam at the All England Club in south-west London, from 28 June to 11 July 2027. The organiser presents the 2027 Championships as its 150-year celebration.', 'CALENDAR_EVENT', 'SPORTS', 'UK', 'QUALIFIED', 'NEW', 'SOURCE_BACKED', 'Claude (Private Calendar launch set, 3 Oct 2026)', 'VERIFIED', 'SPORT', 'London', 'All England Lawn Tennis & Croquet Club', 'United Kingdom', 'London', '2027-06-28', '2027-07-11', 'https://www.wimbledon.com/en_GB/tickets', 'The Championships, Wimbledon', '2026-10-03', 80, 10, 85, 80, 'wimbledon-2027', 'calendarEvent.wimbledon-2027', 'wimbledon|2027-06', 'Dates checked against the organiser’s official site via its search-index text on 3 Oct 2026 (direct page fetch was blocked in the build environment): read the dates on the page before approving. Scores: initial NOYA judgement.')
on conflict (calendar_slug) where calendar_slug is not null do nothing;


insert into approval_audit (action, result, actor, detail)
values ('PRIVATE_CALENDAR_SEED', 'OK', 'system (V3 launch set, 3 Oct 2026)', jsonb_build_object('events', 18, 'status', 'VERIFIED', 'approval', 'pending: Adam via hq_calendar_approve or at APPROVE V3 FINAL'));
