-- NOYA commercial library: 11 products (internal sales frameworks, not public) and 13 playbooks.
-- Cold-email rules baked into every template (what gets replies at this level):
--   * subject: 2–5 words, about THEM (their event / property / project), no hype, no "partnership opportunity";
--   * line 1: the specific trigger, proving we noticed something real — never "I hope this finds you well";
--   * line 2: the operational problem that trigger creates for them (their words, not ours);
--   * line 3: one concrete proof of NOYA on the ground (Egypt team, partners, a comparable delivery);
--   * line 4: one small, specific offer — never a menu of 20 services;
--   * close: one low-friction question (a 15-minute call, or "who handles X?") — never two asks;
--   * under ~90 words, plain text, no attachments, no links on the first touch;
--   * follow-ups add something new each time (a detail, an idea, a referral ask) and stop after the third.
-- Placeholders: {{first_name}} {{company}} {{event}} {{event_date}} {{destination}} {{trigger_detail}} {{proof}}.
-- Sign-off everywhere: Adam Elshazly · Founder, NOYA Concierge · noyaconcierge.com

insert into public.commercial_products (code, name, summary, owner_role, target_segments, ideal_client, buyer_roles, trigger_events, client_problems,
  solution, included_services, proof_points, partner_types, outreach_angles, email_template, dm_template, call_points, objections, proposal_template,
  follow_up_sequence, upsells, recurring_potential)
values
('EVENT_CONCIERGE_DESK', 'NOYA Event Concierge Desk',
 'A dedicated on-ground concierge desk for an event''s international guests, talent and sponsors — before, during and after the event.',
 'EVENTS', array['EVENTS', 'SPORTS', 'ENTERTAINMENT', 'CORPORATE'],
 'An organiser or promoter bringing hundreds of international guests to Egypt for a fixed date.',
 array['Head of Partnerships', 'Commercial Director', 'Event Operations Director', 'Guest Relations Manager', 'Hospitality Manager'],
 array['International event announced for Egypt', 'Festival / race / conference with international attendance', 'Sponsor programme announced'],
 array['International guests arrive with high expectations and no local contacts', 'Organiser team is stretched on event operations, not guest requests', 'Hotels, transfers and dinners booked piecemeal by guests, with no quality control'],
 'One accountable NOYA desk (named lead + 24/7 line) that handles guest arrivals, transport, accommodation, dining and last-minute problems, reporting to the organiser.',
 array['24/7 guest line', 'Airport meet & greet and VIP handling', 'Chauffeured transfers', 'Accommodation sourcing and room blocks', 'Restaurant and nightlife access', 'Pre/post-event experiences', 'On-site concierge desk'],
 array['Egypt ground team with hotel, transport and venue partners', 'Single point of contact for the organiser', 'Rates negotiated through NOYA partners'],
 array['HOTEL', 'TRANSPORT', 'SECURITY', 'RESTAURANT', 'EXPERIENCE'],
 array['Your international guests need a local host you do not have to manage', 'Protect the guest experience outside the venue — the part your team cannot control'],
 $j${"subject": "{{event}} guests in {{destination}}", "body": "Hi {{first_name}},\n\n{{trigger_detail}} — congratulations. With international guests arriving for {{event}}, most of what they judge you on happens outside the venue: arrivals, transfers, where they stay, where they eat.\n\nNOYA runs that layer on the ground in Egypt — one desk, one named lead, a 24/7 line for your guests, and our hotel and transport partners behind it. {{proof}}\n\nWould a 15-minute call next week be useful to see whether a guest desk for {{event}} makes sense?\n\nAdam Elshazly\nFounder, NOYA Concierge"}$j$::jsonb,
 'Hi {{first_name}} — saw {{event}} is coming to {{destination}}. NOYA runs on-ground guest services in Egypt (arrivals, transport, hotels, dining, 24/7 line). Worth a quick chat about your international guests?',
 array['How many international guests, talent and sponsor guests do they expect?', 'Who handles guest requests today — in-house, agency, nobody?', 'Which hotels are they already using?', 'Where did guest experience go wrong at previous editions?', 'Decision timeline and budget owner'],
 $j$[{"objection": "Our agency already handles this.", "response": "Good — we work alongside agencies as their Egypt ground layer. Who at the agency owns the on-ground guest side?"}, {"objection": "Too early / too late.", "response": "Fair. What date would be right to talk guest services — can I put it in both our diaries?"}, {"objection": "Budget is committed.", "response": "Guest services can be paid per guest or by sponsors directly, not from the event budget. Worth a look?"}]$j$::jsonb,
 'Scope: guest profile and volumes · Desk model (on-site hours, 24/7 line) · Services menu with per-guest pricing · Partners and rates · Reporting to organiser · Commercial terms (per-guest fee or fixed desk fee + pass-through costs).',
 $j$[{"day": 3, "channel": "EMAIL", "purpose": "Add one concrete idea", "message": "One practical idea for {{event}}: a single WhatsApp line for all international guests, staffed by NOYA, so your team never fields a hotel or car request. Happy to show how it runs."}, {"day": 7, "channel": "LINKEDIN", "purpose": "Right person", "message": "Hi {{first_name}} — who on your team looks after international guest experience for {{event}}? Happy to take it to them directly."}, {"day": 14, "channel": "EMAIL", "purpose": "Close the loop", "message": "I will leave this here — if guest services for {{event}} become a need, NOYA can be set up within a week. Good luck with the edition."}]$j$::jsonb,
 array['Sponsor guest programme', 'Talent/artist concierge', 'Post-event Egypt extensions', 'Private dinners and after-parties'],
 'Annual — recurring editions become a standing contract.'),

('ATHLETE_TEAM_DESK', 'NOYA Athlete & Team Desk',
 'Travel, accommodation, recovery and lifestyle support for athletes, teams and their entourage in Egypt and abroad.',
 'SALES', array['SPORTS'],
 'Sports organisers, clubs, federations and athlete agencies moving athletes to or through Egypt.',
 array['Athlete Services Manager', 'Team Manager', 'Head of Operations', 'Sports Agent', 'Head of Partnerships'],
 array['International race / tournament in Egypt', 'Training camp announced', 'Team travel to the region', 'Athlete visit'],
 array['Elite athletes need predictable logistics, recovery and privacy', 'Organisers must look after pro athletes and VIP participants', 'Agents cannot manage ground detail in an unfamiliar country'],
 'A named NOYA athlete lead coordinating arrivals, hotels, transport, recovery/wellness providers, nutrition-friendly dining and private time.',
 array['Airport VIP handling', 'Team transport', 'Accommodation near venue', 'Recovery and wellness coordination', 'Private dining', 'Security', 'Post-event travel'],
 array['Egypt partner network (hotels, transport, wellness)', 'Discretion for high-profile individuals'],
 array['HOTEL', 'TRANSPORT', 'WELLNESS', 'SECURITY'],
 array['Pro athletes judge the race by everything around it', 'Take athlete logistics off the race operations team'],
 $j${"subject": "Athletes arriving for {{event}}", "body": "Hi {{first_name}},\n\nWith {{event}} in {{destination}} on {{event_date}}, your pro and international athletes will need the ground to just work — arrivals, rooms near the venue, recovery, food they can race on.\n\nNOYA looks after that in Egypt: one athlete lead, VIP airport handling, transport and our wellness and hotel partners. {{proof}}\n\nWho on your side looks after athlete and VIP participant experience? Happy to send a one-page outline.\n\nAdam Elshazly\nFounder, NOYA Concierge"}$j$::jsonb,
 'Hi {{first_name}} — {{event}} in {{destination}} looks great. NOYA handles athlete and VIP participant logistics on the ground in Egypt. Who looks after that on your side?',
 array['Number of pro/elite athletes and VIP participants', 'Arrival windows', 'Recovery and nutrition needs', 'Official hotel partners', 'Who pays: organiser, athlete, sponsor'],
 $j$[{"objection": "Athletes book themselves.", "response": "Most do — which is where problems start. We can offer it as an optional paid service, zero cost to you."}, {"objection": "We have a travel partner.", "response": "Global travel partners rarely cover ground detail in Egypt. We can be their local layer."}]$j$::jsonb,
 'Athlete profile · Service levels (standard / pro / VIP) · Per-athlete pricing · Partner hotels and rates · On-site support hours.',
 $j$[{"day": 3, "channel": "EMAIL", "purpose": "Concrete idea", "message": "A small idea for {{event}}: a pro-athlete arrival lane — met at the aircraft door, straight to the hotel, recovery booked for race eve. We can run it for your top field."}, {"day": 7, "channel": "LINKEDIN", "purpose": "Right person", "message": "Hi {{first_name}}, who handles athlete services for {{event}}? Happy to take it to them."}, {"day": 14, "channel": "EMAIL", "purpose": "Close", "message": "Closing the loop on {{event}} — if athlete logistics in Egypt come up, NOYA can step in quickly. Good luck with the race."}]$j$::jsonb,
 array['Team training camps', 'Athlete private travel', 'Sponsor hospitality'],
 'Per season / per edition.'),

('BRAND_EXPERIENCE_DESK', 'NOYA Brand Experience Desk',
 'On-ground delivery of brand activations, launches, press trips and VIP brand hospitality in Egypt.',
 'SALES', array['BRANDS', 'LUXURY_GOODS', 'REAL_ESTATE'],
 'Luxury and lifestyle brands (and their agencies) staging launches, activations or VIP programmes in Egypt.',
 array['Head of Events', 'Brand Experience Director', 'Marketing Director', 'PR Director', 'Agency Account Director'],
 array['Brand entering Egypt', 'Launch event announced', 'Activation at an iconic site', 'Press / creator trip'],
 array['Brand standards must hold in an unfamiliar market', 'VIP guests, press and creators need flawless hosting', 'Local suppliers need someone accountable'],
 'NOYA as the brand''s accountable Egypt partner for guest hosting, venues, suppliers and VIP moments, aligned with the brand''s agency.',
 array['VIP guest hosting', 'Press and creator trips', 'Venue and supplier coordination', 'Gifting logistics', 'Private dinners', 'Chauffeurs and security'],
 array['Luxury-standard partner network in Egypt', 'Works alongside the brand''s agency, not against it'],
 array['VENUE', 'HOTEL', 'RESTAURANT', 'PRODUCTION', 'SECURITY'],
 array['Your Egypt moment should feel like your brand, not like a local event', 'An accountable local partner for VIP guests and press'],
 $j${"subject": "{{company}} in {{destination}}", "body": "Hi {{first_name}},\n\nI saw {{trigger_detail}}. When international guests, press and creators fly in for a moment like this, the details between the venue and the hotel are where brands are remembered — or not.\n\nNOYA hosts that layer in Egypt to a luxury standard: VIP arrivals, transport, private dinners, guest requests, with partners we already vouch for. {{proof}}\n\nIs anyone on your side planning guest hosting for Egypt? Happy to share how we would approach it.\n\nAdam Elshazly\nFounder, NOYA Concierge"}$j$::jsonb,
 'Hi {{first_name}} — saw {{company}}''s news in {{destination}}. NOYA hosts VIP guests, press and creators in Egypt to a luxury standard. Worth a quick conversation?',
 array['Guest list profile (VIP, press, creators)', 'Agency involved', 'Brand standards / approvals', 'Dates and venues', 'Budget owner'],
 $j$[{"objection": "Our agency runs everything.", "response": "Perfect — we become the agency's ground partner in Egypt. Could you introduce us?"}, {"objection": "We only work with global suppliers.", "response": "Understood — we can operate under your global supplier's contract as the Egypt layer."}]$j$::jsonb,
 'Objectives · Guest profile · Hosting programme · Suppliers and venues · Timeline · Fees (fixed hosting fee + pass-through).',
 $j$[{"day": 3, "channel": "EMAIL", "purpose": "Idea", "message": "One idea: a private sunrise moment at the Pyramids for your top guests before the main event — we can make it happen quietly."}, {"day": 7, "channel": "LINKEDIN", "purpose": "Right person / agency", "message": "Hi {{first_name}}, is there an agency leading the Egypt programme? Happy to speak with them directly."}, {"day": 14, "channel": "EMAIL", "purpose": "Close", "message": "I will leave it there — if you host guests in Egypt later this year, NOYA is ready."}]$j$::jsonb,
 array['Creator content trips', 'Annual VIP client programme', 'Private shopping / sourcing'],
 'Per activation; brands that return become annual.'),

('EGYPT_DESTINATION_DESK', 'NOYA Egypt Destination Desk',
 'NOYA as the trusted Egypt ground partner for travel companies, concierge firms and agencies abroad (white-label or co-branded).',
 'PARTNERSHIPS', array['TRAVEL', 'PRIVATE_UHNW', 'CORPORATE'],
 'Concierge firms, luxury travel advisors, DMCs and agencies whose clients ask for Egypt.',
 array['Founder', 'Head of Travel', 'Partnerships Director', 'Head of Concierge', 'Operations Director'],
 array['International concierge expanding MENA', 'Travel company adding Egypt', 'Grand Egyptian Museum / new Egypt demand'],
 array['Clients ask for Egypt; they have no trusted ground partner', 'Quality risk when subcontracting unknown DMCs'],
 'A named NOYA team delivering Egypt to their standard, white-label if needed, with agreed commission or net rates.',
 array['Itinerary design', 'Private guiding', 'Hotels and Nile cruises', 'Transfers and security', 'VIP access', 'Private aviation and yachts'],
 array['Egypt-based luxury team', 'Private access to sites and venues'],
 array['HOTEL', 'CRUISE', 'GUIDE', 'TRANSPORT', 'AVIATION'],
 array['Your clients already ask for Egypt', 'A ground partner you can put your name on'],
 $j${"subject": "Egypt for {{company}} clients", "body": "Hi {{first_name}},\n\nEgypt demand has jumped with the Grand Egyptian Museum open and new luxury openings on the Nile and Red Sea — I imagine some of your clients are asking.\n\nNOYA is an Egypt-based luxury concierge. We deliver for partners under their name or ours: private access, hotels, Nile, security, the lot — with net rates or commission, as you prefer.\n\nWould it be useful to have a trusted Egypt partner on file? Happy to send how we work with partners.\n\nAdam Elshazly\nFounder, NOYA Concierge"}$j$::jsonb,
 'Hi {{first_name}} — when your clients ask for Egypt, who delivers on the ground? NOYA is an Egypt-based luxury team working white-label with partners. Open to a quick intro call?',
 array['Current Egypt volume and who delivers it', 'Service standard expectations', 'Commercial model (net / commission / white-label)', 'Response-time expectations'],
 $j$[{"objection": "We already have a DMC in Egypt.", "response": "Many do. We are often the second partner for the high-end requests. Worth comparing on one trip?"}, {"objection": "Low Egypt volume.", "response": "Then a partner on file costs you nothing until a client asks. Shall I send our partner pack?"}]$j$::jsonb,
 'Partnership terms · Service standards · Rate model · Escalation · Branding (white-label / co-brand).',
 $j$[{"day": 4, "channel": "EMAIL", "purpose": "Value", "message": "In case useful: three Egypt experiences your clients will not find online — happy to send a one-page note."}, {"day": 10, "channel": "LINKEDIN", "purpose": "Connect", "message": "Hi {{first_name}}, great to connect — here if any Egypt request comes up."}, {"day": 21, "channel": "EMAIL", "purpose": "Close", "message": "Last note from me — our Egypt partner pack is available whenever a client request comes in."}]$j$::jsonb,
 array['Referral agreement', 'Joint client events', 'Reciprocal destination partnership'],
 'Referral partnership: recurring volume.'),

('VIP_GUEST_DESK', 'NOYA VIP Guest Desk',
 'A discreet VIP host for named guests: celebrities, investors, dignitaries and sponsors.',
 'SALES', array['ENTERTAINMENT', 'PRIVATE_UHNW', 'EVENTS', 'CORPORATE'],
 'Organisers, PR agencies and companies hosting a small number of very important guests.',
 array['Talent Relations Manager', 'PR Director', 'Chief of Staff', 'Head of Protocol', 'Guest Relations Director'],
 array['Celebrity / talent attending an Egypt event', 'Investor or delegation visit', 'VIP launch guest list'],
 array['VIPs expect one flawless point of contact', 'Reputational risk if a VIP has a bad experience'],
 'A named NOYA VIP host per guest group with airport VIP, security, private transport and 24/7 requests.',
 array['Aircraft-side VIP handling', 'Security', 'Private chauffeurs', 'Suites and villas', 'Restaurant and nightlife access', 'Personal assistants'],
 array['Discretion and confidentiality', 'Egypt VIP handling experience'],
 array['SECURITY', 'TRANSPORT', 'HOTEL', 'AVIATION'],
 array['One host your VIPs never have to think about', 'Protect the relationship with your most important guests'],
 $j${"subject": "VIP guests for {{event}}", "body": "Hi {{first_name}},\n\nWith {{event}} on {{event_date}}, I imagine you have a short list of guests whose experience matters more than anyone else's.\n\nNOYA hosts VIPs in Egypt discreetly — met at the aircraft, private transport, security, suites, and one host they can message for anything, day or night.\n\nIf it would help, we can take care of your top guests so your team can focus on the event. Worth a short call?\n\nAdam Elshazly\nFounder, NOYA Concierge"}$j$::jsonb,
 'Hi {{first_name}} — for {{event}}, NOYA can host your top guests discreetly (VIP airport, security, private transport, 24/7 host). Worth a word?',
 array['How many VIPs and their profile', 'Security requirements', 'Confidentiality terms', 'Who approves guest services'],
 $j$[{"objection": "Protocol handles it.", "response": "We support protocol teams with the lifestyle layer — cars, dinners, requests — so they can focus on the programme."}]$j$::jsonb,
 'VIP programme per guest · Security plan · Hosting team · Fees per VIP day + pass-through.',
 $j$[{"day": 3, "channel": "EMAIL", "purpose": "Idea", "message": "A thought: a private arrival lane and a single host per VIP household removes 90% of last-minute issues."}, {"day": 7, "channel": "LINKEDIN", "purpose": "Right person", "message": "Hi {{first_name}}, who looks after VIP guests for {{event}}?"}, {"day": 14, "channel": "EMAIL", "purpose": "Close", "message": "Closing the loop — we remain available for VIP hosting in Egypt."}]$j$::jsonb,
 array['VIP extension trips', 'Private aviation', 'Year-round VIP retainer'],
 'Per event; standing VIP retainers for agencies.'),

('CORPORATE_DESK', 'NOYA Corporate Desk',
 'Executive travel, delegations, offsites and incentive programmes delivered to a luxury standard.',
 'SALES', array['CORPORATE'],
 'Companies and organisers running executive visits, conferences, offsites or incentives in Egypt or abroad.',
 array['Executive Assistant', 'Chief of Staff', 'Head of Events', 'Travel Manager', 'HR / Incentives Lead'],
 array['Conference or summit in Egypt', 'Delegation announced', 'Company expanding into Egypt', 'Incentive trip'],
 array['Executives need reliability and privacy', 'Delegation logistics are complex and time-bound'],
 'A NOYA corporate lead coordinating executive arrivals, transport, hotels, meetings logistics and leisure time.',
 array['Executive airport handling', 'Chauffeurs and security', 'Hotel blocks', 'Meeting venues', 'Dinners', 'Leisure and cultural experiences'],
 array['Executive-grade reliability', 'Single invoice'],
 array['HOTEL', 'TRANSPORT', 'VENUE', 'SECURITY'],
 array['Your executives'' time in Egypt, handled end to end'],
 $j${"subject": "Your delegation for {{event}}", "body": "Hi {{first_name}},\n\nI saw {{company}} is involved in {{event}} in {{destination}}. For senior delegations, the difference is usually made on the ground: who meets them, how they move, where they can talk privately.\n\nNOYA handles executive visits in Egypt end to end — airport, chauffeurs, security, hotels, private dinners — with one lead and one invoice.\n\nIs someone already arranging this for your team? If not, happy to help.\n\nAdam Elshazly\nFounder, NOYA Concierge"}$j$::jsonb,
 'Hi {{first_name}} — if your team is travelling for {{event}}, NOYA handles executive logistics in Egypt end to end. Useful?',
 array['Delegation size and seniority', 'Dates', 'Security needs', 'Current travel provider'],
 $j$[{"objection": "Our travel management company handles it.", "response": "TMCs book flights and hotels; we handle everything on the ground. We work well together."}]$j$::jsonb,
 'Delegation plan · Per-person or fixed fee · Pass-through costs · Security.',
 $j$[{"day": 3, "channel": "EMAIL", "purpose": "Idea", "message": "A detail that tends to matter: a private dinner venue for the leadership group on night one. We can hold options."}, {"day": 7, "channel": "EMAIL", "purpose": "Right person", "message": "Who coordinates travel for your delegation? Happy to speak with them."}, {"day": 14, "channel": "EMAIL", "purpose": "Close", "message": "I will leave it there — NOYA is available whenever your team travels to Egypt."}]$j$::jsonb,
 array['Corporate retainer', 'Executive concierge for staff', 'Annual incentive trip'],
 'Corporate retainers and annual programmes.'),

('NOYA_PRIVATE', 'NOYA Private',
 'Private-client lifestyle management and travel for HNW individuals and families (membership or per request).',
 'SALES', array['PRIVATE_UHNW'],
 'HNW/UHNW individuals and families, often introduced by family offices, private banks and advisers.',
 array['Principal', 'Family Office Director', 'Private Banker', 'Executive / Personal Assistant'],
 array['Relationship introduction', 'Principal travelling to Egypt', 'Family event'],
 array['Time, trust and discretion', 'Inconsistent service across destinations'],
 'A dedicated NOYA lifestyle manager for the family with a trusted partner network.',
 array['Travel', 'Villas and hotels', 'Reservations', 'Private aviation and yachts', 'Events', 'Sourcing'],
 array['Discretion', 'Global network with Egypt strength'],
 array['AVIATION', 'YACHT', 'VILLA', 'HOTEL'],
 array['A lifestyle team that already knows you'],
 $j${"subject": "Introduction via {{company}}", "body": "Hi {{first_name}},\n\n{{trigger_detail}}.\n\nNOYA is a private lifestyle and travel team — one manager for the family, a trusted network behind them, and particular depth in Egypt and the Mediterranean.\n\nIf it would be helpful, I would be glad to have a short conversation about how you like to travel and whether we could be useful.\n\nAdam Elshazly\nFounder, NOYA Concierge"}$j$::jsonb,
 'Hi {{first_name}} — {{trigger_detail}}. Happy to introduce NOYA if useful; no pressure at all.',
 array['How they travel', 'Current providers', 'Upcoming plans', 'Preferred communication'],
 $j$[{"objection": "We have a concierge.", "response": "Many of our clients do — we are often the specialist for Egypt and complex trips."}]$j$::jsonb,
 'Membership tiers or per-request · Service standards · Confidentiality.',
 $j$[{"day": 5, "channel": "EMAIL", "purpose": "Gentle", "message": "Just a gentle note in case timing is better now — no reply needed if not."}]$j$::jsonb,
 array['Membership', 'Family events', 'Sourcing'],
 'Membership / annual retainer.'),

('PRODUCTION_DESK', 'NOYA Production Desk',
 'Ground support for international shoots in Egypt: crew hospitality, transport, locations and supplier coordination (permits via specialist partners).',
 'EVENTS', array['PRODUCTION', 'BRANDS', 'ENTERTAINMENT'],
 'International production companies and agencies shooting films, series, commercials or content in Egypt.',
 array['Producer', 'Line Producer', 'Production Manager', 'Head of Production', 'Location Manager'],
 array['Shoot announced in Egypt', 'Film commission incentive', 'Brand campaign shoot'],
 array['Crew travel, rooms and transport at scale', 'Talent needs VIP care during a shoot', 'Local supplier reliability'],
 'NOYA as the production''s hospitality and ground-logistics partner, working alongside the local fixer and permit specialists.',
 array['Crew accommodation blocks', 'Transport fleets', 'Talent VIP care', 'Location scouting support', 'Catering and dining', 'Equipment and supplier coordination via partners'],
 array['Egypt supplier network', 'Talent hosting experience'],
 array['PRODUCTION', 'TRANSPORT', 'HOTEL', 'SECURITY'],
 array['Keep crew and talent looked after so the shoot stays on schedule'],
 $j${"subject": "Your shoot in Egypt", "body": "Hi {{first_name}},\n\nI saw {{trigger_detail}}. On shoots in Egypt, schedules usually slip because of what happens off set — crew rooms, transport, talent care — rather than on it.\n\nNOYA handles that ground layer: crew accommodation and fleets, VIP care for talent, dining and supplier coordination, working alongside your local fixer and permit partners.\n\nWho is running production logistics on your side? Happy to help where useful.\n\nAdam Elshazly\nFounder, NOYA Concierge"}$j$::jsonb,
 'Hi {{first_name}} — saw you are shooting in Egypt. NOYA handles crew hospitality, transport and talent care on the ground. Who runs production logistics?',
 array['Shoot dates and locations', 'Crew and talent numbers', 'Fixer / service company already hired', 'What is not covered yet'],
 $j$[{"objection": "We have a fixer.", "response": "Great — we complement fixers with hospitality and talent care at a higher standard."}]$j$::jsonb,
 'Production support scope · Crew/talent per-day rates · Pass-through · Contacts.',
 $j$[{"day": 3, "channel": "EMAIL", "purpose": "Idea", "message": "One practical point: we can hold a crew room block near your main location now, released at no cost if dates move."}, {"day": 7, "channel": "LINKEDIN", "purpose": "Right person", "message": "Hi {{first_name}}, who is the line producer on the Egypt shoot?"}, {"day": 14, "channel": "EMAIL", "purpose": "Close", "message": "Closing the loop — available if production logistics in Egypt come up."}]$j$::jsonb,
 array['Talent private travel', 'Wrap events', 'Future shoots'],
 'Repeat productions with the same producers.'),

('WEDDING_GUEST_DESK', 'NOYA Wedding Guest Desk',
 'Guest management for destination weddings: arrivals, accommodation, transport, experiences and a guest help line.',
 'EVENTS', array['WEDDINGS'],
 'Wedding planners and families hosting international guests in Egypt or abroad.',
 array['Wedding Planner', 'Planner Agency Director', 'Family Office', 'Couple'],
 array['Destination wedding announced', 'Planner entering Egypt'],
 array['Hundreds of guests with individual needs', 'Planner capacity during the wedding week'],
 'A NOYA guest desk that handles every guest request so the planner can focus on the wedding.',
 array['Guest arrival management', 'Room blocks', 'Transfers', 'Welcome experiences', 'Guest help line'],
 array['Egypt venues and hotels network'],
 array['HOTEL', 'TRANSPORT', 'VENUE', 'EXPERIENCE'],
 array['Look after every guest so the planner can look after the wedding'],
 $j${"subject": "Guests for your Egypt wedding", "body": "Hi {{first_name}},\n\nFor weddings in Egypt with international guests, the planner's week is usually taken over by guest questions — flights, rooms, cars, what to do on the free day.\n\nNOYA runs a guest desk for planners: arrivals, room blocks, transfers, experiences and one help line for every guest.\n\nIf you have an Egypt wedding coming up, would it help to take the guests off your plate?\n\nAdam Elshazly\nFounder, NOYA Concierge"}$j$::jsonb,
 'Hi {{first_name}} — NOYA runs guest desks for destination weddings in Egypt so planners can focus on the day. Any Egypt weddings on your calendar?',
 array['Guest count and origins', 'Dates', 'Venue and hotels', 'Services not yet covered'],
 $j$[{"objection": "We manage guests ourselves.", "response": "Understood — we can take just arrivals and transfers, the part that eats the most time."}]$j$::jsonb,
 'Guest desk scope · Per-guest fee · Room block terms.',
 $j$[{"day": 4, "channel": "EMAIL", "purpose": "Idea", "message": "An idea couples love: a curated free-day programme for guests (Pyramids at sunrise, a Nile dinner)."}, {"day": 12, "channel": "EMAIL", "purpose": "Close", "message": "Last note — here whenever you plan an Egypt wedding."}]$j$::jsonb,
 array['Honeymoon', 'Pre-wedding events', 'Family travel'],
 'Planner referral partnership.'),

('GLOBAL_TRAVEL_LIFESTYLE', 'NOYA Global Travel & Lifestyle',
 'Global travel planning and lifestyle requests for individuals and corporate clients.',
 'SALES', array['PRIVATE_UHNW', 'CORPORATE', 'TRAVEL'],
 'Clients who want one trusted team for travel and lifestyle anywhere.',
 array['Principal', 'Executive Assistant', 'Chief of Staff'],
 array['Existing client travelling abroad', 'Seasonal peaks (summer, ski, Monaco, Art Basel)'],
 array['Fragmented providers', 'Last-minute access'],
 'One NOYA team handling travel, reservations and access globally.',
 array['Flights and private aviation', 'Hotels and villas', 'Reservations', 'Events access', 'Transfers'],
 array['Partner network in Europe and GCC'],
 array['AVIATION', 'HOTEL', 'VILLA', 'YACHT'],
 array['One team for every trip'],
 $j${"subject": "{{destination}} this season", "body": "Hi {{first_name}},\n\n{{trigger_detail}}.\n\nNOYA plans and runs travel and lifestyle requests for a small number of clients — villas, yachts, tables, access — with partners we know personally.\n\nIf anything is coming up, I would be glad to help. Shall I send a couple of options?\n\nAdam Elshazly\nFounder, NOYA Concierge"}$j$::jsonb,
 'Hi {{first_name}} — anything coming up this season we can take off your plate?',
 array['Upcoming travel', 'Preferences', 'Decision maker'],
 '[]'::jsonb, 'Trip proposal with options and pricing.',
 $j$[{"day": 5, "channel": "EMAIL", "purpose": "Options", "message": "Two options held for you, in case helpful — no obligation."}]$j$::jsonb,
 array['NOYA Private membership'], 'Repeat trips.'),

('LUXURY_SOURCING', 'NOYA Luxury Sourcing',
 'Sourcing hard-to-find luxury goods, experiences and access for clients and brands.',
 'SALES', array['LUXURY_GOODS', 'PRIVATE_UHNW'],
 'Private clients, brands and corporates needing rare items, gifts or access.',
 array['Principal', 'Executive Assistant', 'Brand Gifting Manager'],
 array['Gifting season', 'VIP event gifting', 'Specific request'],
 array['Scarcity', 'Authenticity', 'Timing'],
 'NOYA sources through trusted channels with authenticity checks and delivery.',
 array['Gifts', 'Limited items', 'Experience access', 'Delivery'],
 array['Trusted sourcing network'],
 array['LUXURY_GOODS'],
 array['Find the impossible, reliably'],
 $j${"subject": "Gifting for {{event}}", "body": "Hi {{first_name}},\n\nFor guests at {{event}}, a gift that feels chosen for them tends to be remembered long after the evening.\n\nNOYA sources and delivers luxury gifts and hard-to-find items — authenticated, wrapped, on time.\n\nWould it help to see a few ideas for your guest list?\n\nAdam Elshazly\nFounder, NOYA Concierge"}$j$::jsonb,
 'Hi {{first_name}} — NOYA sources and delivers luxury gifts and rare items. Any gifting coming up?',
 array['Budget per gift', 'Quantity', 'Deadline'], '[]'::jsonb, 'Options with prices.',
 $j$[{"day": 5, "channel": "EMAIL", "purpose": "Ideas", "message": "Three gift ideas attached in the body, if useful."}]$j$::jsonb,
 array['Annual gifting programme'], 'Seasonal gifting.')
on conflict (code) do update set name = excluded.name, summary = excluded.summary, owner_role = excluded.owner_role, target_segments = excluded.target_segments,
  ideal_client = excluded.ideal_client, buyer_roles = excluded.buyer_roles, trigger_events = excluded.trigger_events, client_problems = excluded.client_problems,
  solution = excluded.solution, included_services = excluded.included_services, proof_points = excluded.proof_points, partner_types = excluded.partner_types,
  outreach_angles = excluded.outreach_angles, email_template = excluded.email_template, dm_template = excluded.dm_template, call_points = excluded.call_points,
  objections = excluded.objections, proposal_template = excluded.proposal_template, follow_up_sequence = excluded.follow_up_sequence, upsells = excluded.upsells,
  recurring_potential = excluded.recurring_potential, updated_at = now();

-- ---------------------------------------------------------------- playbooks
insert into public.commercial_playbooks (code, name, trigger_desc, categories, keywords, priority, track, owner_role, ideal_prospect, decision_roles,
  product_codes, value_proposition, services, research_questions, outreach_approach, proposal_type, objections, proof_required, upsells,
  partnership_potential, target_orgs)
values
('SPORTS_EVENT_EGYPT', 'International sporting event entering Egypt',
 'An international race, tournament or sports series announces an edition in Egypt.',
 array['SPORTS'], array['hyrox', 'marathon', 'championship', 'tournament', 'grand prix', 'world cup', 'race', 'padel', 'golf', 'tennis', 'triathlon', 'ironman', 'football', 'league', 'squash'], 90,
 'EVENT', 'EVENTS', 'The rights-holder / local licensee and their sponsors.',
 array['Head of Partnerships', 'Commercial Director', 'Event Operations Director', 'International Expansion Lead', 'Hospitality Manager', 'VIP / Athlete Services', 'Regional Manager', 'Sponsorship Director'],
 array['EVENT_CONCIERGE_DESK', 'ATHLETE_TEAM_DESK', 'VIP_GUEST_DESK'],
 'Become the official local concierge / guest-services partner: athletes, staff, sponsors and international participants handled by one NOYA desk.',
 array['Official concierge partner', 'VIP guest services', 'International athlete concierge', 'Team/staff accommodation', 'Airport VIP handling', 'Chauffeur/ground transport', 'Hospitality partner', 'Sponsor guest concierge', 'Private dining', 'Recovery/wellness coordination', 'Destination experiences', 'Post-event travel', '24/7 local support desk'],
 array['Who holds the Egypt licence / organises locally?', 'Venue and date confirmed?', 'Expected international participants?', 'Official hotel partner?', 'Sponsors announced?', 'Who runs participant experience?'],
 'Lead with the licensee''s Head of Partnerships (official partner angle); in parallel the Operations lead (athlete/staff logistics); later sponsors (guest programmes). One thread per organisation.',
 'Official partner proposal: desk model + per-participant menu + sponsor guest packages.',
 $j$[{"objection": "Global HQ decides partners.", "response": "Local delivery partners are usually chosen locally — who at the Egypt licensee owns that?"}]$j$::jsonb,
 array['Event/guest delivery examples', 'Partner hotels and fleet', 'Insurance and security set-up'],
 array['Annual edition contract', 'Sponsor hospitality', 'Athlete post-race Egypt trips'],
 'High — organisers and their sponsors become recurring distribution partners.',
 $j$[{"org_role": "ORGANISER", "why": "Official concierge / guest services partner", "product": "EVENT_CONCIERGE_DESK", "track": "EVENT"},
     {"org_role": "ORGANISER", "why": "Pro athletes and staff logistics", "product": "ATHLETE_TEAM_DESK", "track": "EVENT"},
     {"org_role": "SPONSOR", "why": "Sponsor guest hospitality", "product": "VIP_GUEST_DESK", "track": "SALES"},
     {"org_role": "HOTEL", "why": "Room blocks and preferred rates", "product": "EVENT_CONCIERGE_DESK", "track": "PARTNERSHIP"}]$j$::jsonb),

('FESTIVAL_ENTERTAINMENT', 'Major festival / international entertainment event',
 'A music festival, concert series or entertainment event with international artists and guests.',
 array['ENTERTAINMENT', 'EVENTS'], array['festival', 'concert', 'dj', 'music', 'tour', 'live', 'lineup', 'exit', 'starlight', 'rave', 'performance'], 80,
 'EVENT', 'EVENTS', 'The promoter / organiser and their local partner; sponsors; artist agencies.',
 array['Festival Director', 'Head of Artist Relations', 'Head of Partnerships', 'Hospitality / VIP Manager', 'Sponsorship Director', 'Local Promoter'],
 array['EVENT_CONCIERGE_DESK', 'VIP_GUEST_DESK', 'BRAND_EXPERIENCE_DESK'],
 'Artist concierge and international guest services on the ground, plus sponsor and VIP table hospitality.',
 array['Artist concierge', 'Artist transport', 'International guest concierge', 'Sponsor hospitality', 'VIP table/guest handling', 'Hotel room blocks', 'Luxury transport', 'Private aviation', 'Security', 'Restaurant/nightlife', 'Private pre/post events', 'Destination extensions', 'Creator attendance', 'Brand collaborations', 'Promoter local support'],
 array['Who is the international promoter and the local partner?', 'Artist count and arrival days?', 'VIP / table programme?', 'Hotel partner?', 'Sponsors?'],
 'Artist Relations first (clear operational pain), then VIP/hospitality, then sponsors. Keep it short and practical — promoters are busy in the final weeks.',
 'Artist + VIP desk proposal with per-artist and per-guest pricing; sponsor hospitality packages.',
 $j$[{"objection": "Our artist liaison team covers it.", "response": "We plug in under your liaison team for Egypt-specific ground detail."}]$j$::jsonb,
 array['Talent handling references', 'Fleet and security partners'],
 array['Pre/post parties', 'Artist Egypt experiences', 'Next edition'],
 'Promoters return yearly; artist agencies refer.',
 $j$[{"org_role": "ORGANISER", "why": "Artist and international guest concierge", "product": "EVENT_CONCIERGE_DESK", "track": "EVENT"},
     {"org_role": "PROMOTER", "why": "VIP guest and table handling", "product": "VIP_GUEST_DESK", "track": "EVENT"},
     {"org_role": "SPONSOR", "why": "Sponsor hospitality and activation", "product": "BRAND_EXPERIENCE_DESK", "track": "SALES"}]$j$::jsonb),

('FILM_FESTIVAL', 'Film festival',
 'A film festival with international talent, press, sponsors and guests (e.g. El Gouna, Cairo International).',
 array['ENTERTAINMENT', 'EVENTS'], array['film festival', 'cinema', 'premiere', 'red carpet', 'gouna', 'ciff', 'screening'], 95,
 'EVENT', 'EVENTS', 'Festival organisation (guest relations, hospitality, partnerships), sponsors, agencies, talent agencies.',
 array['Festival Director', 'Head of Guest Relations', 'Head of Hospitality', 'Partnerships / Sponsorship Director', 'Talent Relations', 'PR Director', 'Production Manager'],
 array['VIP_GUEST_DESK', 'EVENT_CONCIERGE_DESK', 'BRAND_EXPERIENCE_DESK', 'PRODUCTION_DESK'],
 'NOYA contributes across talent, VIP guest services, accommodation, travel, hospitality, brand/sponsor support, production and partner activation — not just reservations and cars.',
 array['Creator / talent introductions and hosting', 'Dedicated guest concierge', 'Airport meet & greet and VIP handling', 'Chauffeured transport', 'Security', 'Restaurant and nightlife access', 'Personal assistants', 'Hotels, suites, villas and overflow', 'Talent/guest room blocks', 'Private aviation and yachts', 'Cairo–El Gouna transfers', 'Private dinners, buyouts, after-parties', 'Beach days and Red Sea experiences', 'Pyramids/Cairo extensions', 'Sponsor guest concierge and activations', 'Gifting logistics', 'Crew transport and accommodation', 'Hotel, restaurant and beach-club partner activation'],
 array['Who runs guest relations and hospitality?', 'How many international guests / talent?', 'Which sponsors and agencies are involved?', 'Accommodation pressure in the destination during festival week?', 'Which brands host events?'],
 'Several parallel, role-specific threads: guest relations (VIP desk), partnerships (official concierge), each sponsor (brand hosting), agencies (ground partner), talent agencies (artist care). Never one generic email to the festival.',
 'Menu proposal by audience: talent, VIP guests, sponsors, press — per-guest and per-event pricing.',
 $j$[{"objection": "The resort handles guests.", "response": "The resort is the stage; we cover everything guests need beyond it — arrivals, Cairo extensions, private moments."}]$j$::jsonb,
 array['VIP hosting references', 'Talent/creator relationships', 'Accommodation partners in the destination'],
 array['Year-round talent hosting', 'Sponsor annual programme', 'Next edition'],
 'Very high — one festival opens sponsors, agencies and talent.',
 $j$[{"org_role": "ORGANISER", "why": "VIP guest services and guest relations support", "product": "VIP_GUEST_DESK", "track": "EVENT"},
     {"org_role": "ORGANISER", "why": "Official concierge desk for international guests", "product": "EVENT_CONCIERGE_DESK", "track": "EVENT"},
     {"org_role": "SPONSOR", "why": "Sponsor guest hospitality and activations", "product": "BRAND_EXPERIENCE_DESK", "track": "SALES"},
     {"org_role": "AGENCY", "why": "Ground partner for agency programmes", "product": "BRAND_EXPERIENCE_DESK", "track": "PARTNERSHIP"},
     {"org_role": "TALENT_AGENCY", "why": "Talent travel and care", "product": "VIP_GUEST_DESK", "track": "PARTNERSHIP"},
     {"org_role": "HOTEL", "why": "Guest room blocks and preferred rates", "product": "EVENT_CONCIERGE_DESK", "track": "PARTNERSHIP"}]$j$::jsonb),

('BRAND_ACTIVATION', 'International brand activation',
 'An international brand enters Egypt, launches a product, or stages an activation / show.',
 array['BRANDS', 'LUXURY_GOODS'], array['launch', 'activation', 'pop-up', 'boutique', 'flagship', 'show', 'collection', 'brand', 'campaign', 'unveil'], 70,
 'SALES', 'SALES', 'The brand''s events/marketing lead and its agency.',
 array['Head of Events', 'Marketing Director', 'Brand Experience Director', 'PR Director', 'Agency Account Director'],
 array['BRAND_EXPERIENCE_DESK', 'VIP_GUEST_DESK', 'LUXURY_SOURCING'],
 'The brand''s accountable Egypt host for VIP guests, press and creators.',
 array['VIP guest hosting', 'Press/creator trips', 'Venue and supplier coordination', 'Gifting', 'Private dinners', 'Security'],
 array['Which agency runs it?', 'Guest profile?', 'Dates/venue?'],
 'Brand events lead + agency in parallel; lead with guest experience, not logistics.',
 'Hosting programme proposal.', '[]'::jsonb, array['Luxury hosting references'], array['Creator trips', 'Annual VIP programme'],
 'Agencies become repeat partners.',
 $j$[{"org_role": "BRAND", "why": "VIP guest and press hosting", "product": "BRAND_EXPERIENCE_DESK", "track": "SALES"},
     {"org_role": "AGENCY", "why": "Egypt ground partner for the agency", "product": "BRAND_EXPERIENCE_DESK", "track": "PARTNERSHIP"},
     {"org_role": "DEVELOPER", "why": "VIP investor/guest hosting at launches", "product": "VIP_GUEST_DESK", "track": "SALES"}]$j$::jsonb),

('HOTEL_OPENING', 'Luxury hotel / resort opening',
 'A luxury hotel, resort, cruise or beach club opens or announces an opening.',
 array['HOSPITALITY'], array['opening', 'opens', 'reopen', 'launch', 'resort', 'hotel', 'dahabeya', 'cruise', 'beach club', 'suites'], 60,
 'PARTNERSHIP', 'PARTNERSHIPS', 'The property''s commercial / sales & marketing leadership.',
 array['General Manager', 'Director of Sales & Marketing', 'Director of Commercial', 'PR Manager', 'Guest Experience Manager'],
 array['EGYPT_DESTINATION_DESK', 'VIP_GUEST_DESK'],
 'Preferred-partner relationship: NOYA sends qualified guests and events; the property gives preferred rates, access and content collaboration.',
 array['Preferred rates', 'Room allocations for events', 'Content/creator stays', 'VIP guest programmes', 'Event venue use'],
 array['Opening date?', 'Positioning and room count?', 'Who leads sales?', 'Travel-trade programme?'],
 'Partnerships angle: what NOYA brings them (qualified guests, events, creators), then what we need (rates, access).',
 'Preferred partner agreement.', '[]'::jsonb, array['Guest volume evidence', 'Creator reach'], array['Event hosting', 'Content trips'],
 'Supply partner (rates) that also refers guests.',
 $j$[{"org_role": "HOTEL", "why": "Preferred partner: rates, access and events", "product": "EGYPT_DESTINATION_DESK", "track": "PARTNERSHIP"},
     {"org_role": "OPERATOR", "why": "Group-level travel-trade relationship", "product": "EGYPT_DESTINATION_DESK", "track": "PARTNERSHIP"}]$j$::jsonb),

('HOSPITALITY_EXPANSION', 'Hospitality group expansion',
 'A hospitality group expands in Egypt or the region (new brands, portfolios, management deals).',
 array['HOSPITALITY', 'REAL_ESTATE'], array['expands', 'expansion', 'portfolio', 'management agreement', 'group', 'appoints', 'signs'], 55,
 'PARTNERSHIP', 'PARTNERSHIPS', 'Group commercial and partnerships leadership.',
 array['Chief Commercial Officer', 'VP Sales', 'Regional Director of Sales', 'Partnerships Director'],
 array['EGYPT_DESTINATION_DESK'], 'Group-level preferred partnership across properties.',
 array['Group preferred rates', 'Events', 'Guest referrals'], array['Which properties?', 'Group sales lead?'],
 'Group-level conversation after one property relationship proves value.', 'Group partner agreement.', '[]'::jsonb, array['Property-level results'], array['Multi-property events'],
 'Strategic supply partner once productive.',
 $j$[{"org_role": "OPERATOR", "why": "Group preferred partnership", "product": "EGYPT_DESTINATION_DESK", "track": "PARTNERSHIP"}]$j$::jsonb),

('PRODUCTION_SHOOT', 'International production / shoot in Egypt',
 'An international film, series, commercial or content production shoots in Egypt.',
 array['PRODUCTION'], array['shoot', 'shooting', 'filming', 'film commission', 'production', 'crew', 'on location', 'series', 'commercial'], 75,
 'SALES', 'EVENTS', 'The production company''s producer / line producer and the local service company.',
 array['Producer', 'Line Producer', 'Production Manager', 'Location Manager', 'Service Company Director'],
 array['PRODUCTION_DESK', 'VIP_GUEST_DESK'], 'Crew hospitality, transport and talent care so the shoot stays on schedule.',
 array['Crew accommodation', 'Transport fleet', 'Talent VIP care', 'Catering/dining', 'Supplier coordination via partners'],
 array['Which production company?', 'Local service company?', 'Dates and locations?', 'Talent attached?'],
 'Line producer first; the local service company as a partner, never a competitor.', 'Production support scope with per-day rates.', '[]'::jsonb,
 array['Supplier network', 'Talent care references'], array['Wrap events', 'Talent private travel'], 'Service companies refer repeat productions.',
 $j$[{"org_role": "PRODUCTION", "why": "Crew hospitality and talent care", "product": "PRODUCTION_DESK", "track": "SALES"},
     {"org_role": "AGENCY", "why": "Local service company partnership", "product": "PRODUCTION_DESK", "track": "PARTNERSHIP"}]$j$::jsonb),

('CORPORATE_DELEGATION', 'Corporate delegation / conference',
 'A conference, summit or delegation brings senior international attendees to Egypt.',
 array['CORPORATE'], array['conference', 'summit', 'forum', 'delegation', 'congress', 'expo', 'exhibition', 'investment', 'ministerial'], 60,
 'SALES', 'SALES', 'Organiser hospitality lead; attending companies'' executive assistants and event teams.',
 array['Head of Events', 'Protocol / Hospitality Lead', 'Executive Assistant', 'Chief of Staff'],
 array['CORPORATE_DESK', 'VIP_GUEST_DESK'], 'Executive arrivals, transport, security and private dinners handled end to end.',
 array['Executive airport handling', 'Chauffeurs', 'Security', 'Hotel blocks', 'Private dinners', 'Cultural visits'],
 array['Organiser?', 'Attendee profile?', 'Official hotels?', 'Who handles delegate services?'],
 'Organiser hospitality first; attending delegations second.', 'Delegate services proposal.', '[]'::jsonb, array['Executive handling references'],
 array['Corporate retainer'], 'Organisers repeat annually.',
 $j$[{"org_role": "ORGANISER", "why": "Delegate / VIP services", "product": "CORPORATE_DESK", "track": "EVENT"},
     {"org_role": "GOVERNMENT", "why": "VIP delegation hospitality (via official channels)", "product": "VIP_GUEST_DESK", "track": "EVENT"}]$j$::jsonb),

('DESTINATION_WEDDING', 'Destination wedding',
 'A destination wedding or planner programme with international guests.',
 array['WEDDINGS'], array['wedding', 'bride', 'groom', 'engagement', 'planner', 'nuptials'], 70,
 'EVENT', 'EVENTS', 'Wedding planners and families.', array['Wedding Planner', 'Planner Director', 'Family Office'],
 array['WEDDING_GUEST_DESK'], 'Guest desk so the planner can focus on the wedding.',
 array['Guest arrivals', 'Room blocks', 'Transfers', 'Experiences', 'Help line'], array['Planner?', 'Guest count?', 'Dates?'],
 'Planner-first; never approach families cold.', 'Guest desk proposal.', '[]'::jsonb, array['Venue network'], array['Honeymoon'], 'Planners refer repeatedly.',
 $j$[{"org_role": "AGENCY", "why": "Planner guest desk partnership", "product": "WEDDING_GUEST_DESK", "track": "PARTNERSHIP"}]$j$::jsonb),

('PROPERTY_LAUNCH', 'Luxury property launch',
 'A luxury residential / branded-residence developer launches in Egypt or targets Egypt buyers.',
 array['REAL_ESTATE'], array['residential', 'residences', 'branded residence', 'property', 'real estate', 'compound', 'villas', 'developer', 'sales office', 'islands'], 60,
 'SALES', 'SALES', 'Developer marketing/sales leadership.', array['Marketing Director', 'Head of Sales', 'Events Manager', 'Chief Commercial Officer'],
 array['VIP_GUEST_DESK', 'BRAND_EXPERIENCE_DESK', 'NOYA_PRIVATE'],
 'VIP investor hosting at launches and a lifestyle-service layer for buyers.',
 array['VIP investor hosting', 'Launch events', 'Buyer concierge'], array['Launch dates?', 'Buyer profile?', 'Events planned?'],
 'Marketing/events lead; offer buyer concierge as a sales tool.', 'Launch hosting + buyer concierge proposal.', '[]'::jsonb, array['VIP hosting references'],
 array['Residents concierge retainer'], 'Developer as distribution partner to buyers.',
 $j$[{"org_role": "DEVELOPER", "why": "VIP investor hosting and buyer concierge", "product": "VIP_GUEST_DESK", "track": "SALES"},
     {"org_role": "DEVELOPER", "why": "Residents concierge partnership", "product": "NOYA_PRIVATE", "track": "PARTNERSHIP"}]$j$::jsonb),

('VIP_VISIT', 'Athlete / celebrity visit',
 'A known athlete, celebrity or team visits or plans to visit Egypt.',
 array['SPORTS', 'PRIVATE_UHNW', 'ENTERTAINMENT'], array['visit', 'visits', 'celebrity', 'star', 'athlete', 'footballer', 'camp', 'holiday'], 50,
 'SALES', 'SALES', 'Their management, agency or club.', array['Manager', 'Agent', 'Team Manager', 'Personal Assistant'],
 array['VIP_GUEST_DESK', 'NOYA_PRIVATE'], 'Discreet end-to-end hosting.', array['VIP airport', 'Security', 'Private transport', 'Villas', 'Experiences'],
 array['Who manages them?', 'Dates?'], 'Only via management/agency; never approach the individual cold.', 'VIP hosting proposal.', '[]'::jsonb,
 array['Discretion'], array['Repeat private travel'], 'Agencies refer clients.',
 $j$[{"org_role": "TALENT_AGENCY", "why": "Talent visit hosting", "product": "VIP_GUEST_DESK", "track": "SALES"}]$j$::jsonb),

('CONCIERGE_EGYPT_SUPPORT', 'International concierge needing Egypt support',
 'An international concierge, travel or lifestyle company expands to MENA or shows Egypt demand.',
 array['TRAVEL', 'PRIVATE_UHNW'], array['concierge', 'lifestyle management', 'travel company', 'luxury travel', 'dmc', 'members'], 50,
 'PARTNERSHIP', 'PARTNERSHIPS', 'Founders and partnerships leads.', array['Founder', 'Head of Partnerships', 'Head of Concierge'],
 array['EGYPT_DESTINATION_DESK'], 'Trusted white-label Egypt partner.', array['White-label delivery', 'Commission', 'Priority access'],
 array['Egypt demand?', 'Current ground partner?'], 'Partner-to-partner, peer tone.', 'Partner agreement.', '[]'::jsonb, array['Partner references'],
 array['Reciprocal referrals'], 'Core distribution partner.',
 $j$[{"org_role": "OPERATOR", "why": "White-label Egypt partner", "product": "EGYPT_DESTINATION_DESK", "track": "PARTNERSHIP"}]$j$::jsonb),

('CONTENT_TRIP', 'Brand / influencer content trip',
 'A brand, tourism board or creator plans a content trip.',
 array['BRANDS', 'TRAVEL', 'ENTERTAINMENT'], array['creator', 'influencer', 'content trip', 'press trip', 'fam trip', 'content'], 45,
 'SALES', 'SALES', 'Brand/agency marketing and creator managers.', array['Marketing Manager', 'Creator Partnerships Lead', 'PR Manager', 'Talent Manager'],
 array['BRAND_EXPERIENCE_DESK'], 'Content trips produced to a luxury standard with partner properties.',
 array['Itinerary', 'Partner stays', 'Access', 'Logistics', 'Production support'], array['Who pays?', 'Deliverables?'],
 'Pair a partner property with a creator brief.', 'Trip proposal.', '[]'::jsonb, array['Creator relationships'], array['Recurring content series'],
 'Hotels and brands as partners.',
 $j$[{"org_role": "BRAND", "why": "Content trip production", "product": "BRAND_EXPERIENCE_DESK", "track": "SALES"},
     {"org_role": "HOTEL", "why": "Partner stays for content", "product": "EGYPT_DESTINATION_DESK", "track": "PARTNERSHIP"}]$j$::jsonb)
on conflict (code) do update set name = excluded.name, trigger_desc = excluded.trigger_desc, categories = excluded.categories, keywords = excluded.keywords,
  priority = excluded.priority, track = excluded.track, owner_role = excluded.owner_role, ideal_prospect = excluded.ideal_prospect,
  decision_roles = excluded.decision_roles, product_codes = excluded.product_codes, value_proposition = excluded.value_proposition, services = excluded.services,
  research_questions = excluded.research_questions, outreach_approach = excluded.outreach_approach, proposal_type = excluded.proposal_type,
  objections = excluded.objections, proof_required = excluded.proof_required, upsells = excluded.upsells,
  partnership_potential = excluded.partnership_potential, target_orgs = excluded.target_orgs, updated_at = now();

-- Default follow-up sequence for playbooks = the lead product's sequence (kept in one place).
update public.commercial_playbooks p set follow_up_sequence = coalesce((select follow_up_sequence from commercial_products where code = p.product_codes[1]), '[]')
 where follow_up_sequence = '[]'::jsonb;
